// WidgetKing — Scriptable renderer
// Paste this whole file into a new script in the free Scriptable app.
// This reference copy is generated from the web designer's embedded template
// (web/index.html) with a sample design; the designer's "Copy Scriptable
// Script" button produces the same code with YOUR designs embedded.
//
// Widget "Parameter": "Design Name" or "Design Name | position" (position
// aligns Glass/Clear wallpaper slices). Run the script inside Scriptable to
// set the wallpaper photo for Glass/Clear backgrounds, or to switch Clear
// alignment for the Large-icons (labels hidden) Home Screen.

// WidgetKing — Scriptable renderer (generated by the WidgetKing web designer)
// Widget "Parameter" = design name chooses which design a widget shows.

const DESIGNS = [
  {
    "id": "sample-1",
    "name": "Clock",
    "kind": "clock",
    "themeID": "royal",
    "fontStyle": "rounded",
    "textColorHex": "#FFFFFF",
    "primaryText": "",
    "secondaryText": "",
    "targetDate": "",
    "background": "gradient",
    "glassTint": "dark",
    "canvasElements": [],
    "apps": []
  }
];

const THEMES = {
  midnight: ["#232526", "#414345"], royal: ["#5B2C98", "#8E44AD"],
  sunset: ["#FF512F", "#F09819"], ocean: ["#1A2980", "#26D0CE"],
  forest: ["#134E5E", "#71B280"], candy: ["#FC5C7D", "#6A82FB"],
  lava: ["#870000", "#190A05"], gold: ["#B8860B", "#FFD700"],
  berry: ["#8E2DE2", "#4A00E0"], mist: ["#606C88", "#3F4C6B"],
  mint: ["#02AABD", "#00CDAC"], paper: ["#F5F5F0", "#E4E0D8"]
};
const SYMBOL_EMOJI = {
  "star.fill": "⭐", "heart.fill": "❤️", "bolt.fill": "⚡",
  "moon.stars.fill": "🌙", "sun.max.fill": "☀️", "cloud.fill": "☁️",
  "leaf.fill": "🍃", "flame.fill": "🔥", "sparkles": "✨",
  "music.note": "🎵", "pawprint.fill": "🐾", "crown.fill": "👑"
};

function fontFor(style, size, bold) {
  if (style === "serif") return new Font(bold ? "Georgia-Bold" : "Georgia", size);
  if (style === "mono") return bold ? Font.boldMonospacedSystemFont(size) : Font.regularMonospacedSystemFont(size);
  if (style === "classic") return bold ? Font.boldSystemFont(size) : Font.systemFont(size);
  return bold ? Font.boldRoundedSystemFont(size) : Font.regularRoundedSystemFont(size);
}
function themeColors(d) {
  if (d.themeID === "custom" && d.customColors && d.customColors.length === 2) return d.customColors;
  return THEMES[d.themeID] || THEMES.midnight;
}
function daysUntil(iso) {
  if (!iso) return 0;
  const p = iso.split("-").map(Number);
  const target = new Date(p[0], (p[1] || 1) - 1, p[2] || 1);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  return Math.round((target - today) / 86400000);
}
function centeredText(w, str, font, color) {
  const t = w.addText(str);
  t.font = font; t.textColor = color; t.centerAlignText(); t.minimumScaleFactor = 0.5;
  return t;
}
function hexToRgb(hex) {
  const c = hex.replace("#", "");
  return [parseInt(c.substring(0,2),16), parseInt(c.substring(2,4),16), parseInt(c.substring(4,6),16)];
}
function rgbToHex(rgb) {
  return "#" + rgb.map(function (v) {
    return Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0");
  }).join("");
}

// ---- Transparent / glass backgrounds (wallpaper slice, Koco-style) ----
function wallpaperPath() {
  const fm = FileManager.local();
  return fm.joinPath(fm.documentsDirectory(), "widgetking-wallpaper.jpg");
}
function loadWallpaper() {
  try {
    const fm = FileManager.local();
    const path = wallpaperPath();
    if (fm.fileExists(path)) return fm.readImage(path);
  } catch (e) {}
  return null;
}
// Exact widget frames per iPhone, measured by the Scriptable community
// (mzeryck's Widget Blur data), keyed by the screenshot's pixel height.
// Each frame: [small, medium, large, left, right, top, middle, bottom].
// "labels" = normal Home Screen; "nolabels" = iOS Large-icons mode (labels
// hidden), which shifts the whole grid — toggle it in the in-app menu.
const SCREEN_FRAMES = {
  "2868": { labels: [510, 1092, 1146, 114, 696, 276, 912, 1548], nolabels: [530, 1138, 1136, 91, 699, 276, 882, 1488] },
  "2796": { labels: [510, 1092, 1146, 98, 681, 252, 888, 1524], nolabels: [530, 1139, 1136, 75, 684, 252, 858, 1464] },
  "2622": { labels: [486, 1032, 1098, 87, 633, 261, 872, 1485], nolabels: [495, 1037, 1035, 84, 626, 270, 810, 1350] },
  "2556": { labels: [474, 1017, 1062, 81, 624, 240, 828, 1416], nolabels: [495, 1047, 1047, 66, 618, 243, 795, 1347] },
  "2778": { labels: [510, 1092, 1146, 96, 678, 246, 882, 1518] },
  "2688": { labels: [507, 1080, 1137, 81, 654, 228, 858, 1488] },
  "2532": { labels: [474, 1014, 1062, 78, 618, 231, 819, 1407] },
  "2436": { labels: [465, 987, 1035, 69, 591, 213, 783, 1353] },
  "2079": { labels: [423, 875, 933, 42, 494, 186, 696, 1206] },
  "1792": { labels: [338, 720, 758, 55, 437, 159, 579, 999] },
  "1624": { labels: [310, 658, 690, 46, 394, 142, 522, 902] },
  "1334": { labels: [296, 642, 648, 54, 400, 60, 412, 764], nolabels: [309, 667, 667, 41, 399, 67, 425, 783] }
};
function prefsPath() {
  const fm = FileManager.local();
  return fm.joinPath(fm.documentsDirectory(), "widgetking-prefs.json");
}
function loadPrefs() {
  try {
    const fm = FileManager.local();
    if (fm.fileExists(prefsPath())) return JSON.parse(fm.readString(prefsPath())) || {};
  } catch (e) {}
  return {};
}
function savePrefs(prefs) {
  try { FileManager.local().writeString(prefsPath(), JSON.stringify(prefs)); } catch (e) {}
}
function widgetRect(imgW, imgH, family, position) {
  const pos = position || (family === "small" ? "top-left" : "top");
  const posParts = pos.split("-");
  const row = posParts[0] || "top";
  const side = posParts[1] || "left";
  const entry = SCREEN_FRAMES[String(Math.round(imgH))];
  let x, y, w, h, rows;
  if (entry) {
    const f = (loadPrefs().iconLabels === false && entry.nolabels) ? entry.nolabels : entry.labels;
    rows = { top: f[5], middle: f[6], bottom: f[7] };
    x = f[3];
    w = h = f[0];
    if (family === "small") {
      x = side === "right" ? f[4] : f[3];
    } else if (family === "medium") {
      w = f[1];
    } else if (family === "large") {
      w = f[1]; h = f[2];
    }
  } else {
    // Unknown screenshot size (e.g. a scaled photo) — proportional fallback.
    const sw = Math.round(imgW * 0.402);
    const gap = Math.round((imgW - 2 * sw) / 3);
    const rowStep = sw + gap;
    const top = Math.round(imgH * 0.0965);
    rows = { top: top, middle: top + rowStep, bottom: top + 2 * rowStep };
    x = gap;
    w = h = sw;
    if (family === "small") {
      x = side === "right" ? gap * 2 + sw : gap;
    } else if (family === "medium") {
      w = imgW - 2 * gap;
    } else if (family === "large") {
      w = imgW - 2 * gap; h = sw * 2 + gap;
    }
  }
  y = rows[row] != null ? rows[row] : rows.top;
  if (family === "large" && row === "bottom") y = rows.middle;
  if (y + h > imgH) y = Math.max(0, imgH - h);
  return new Rect(x, y, w, h);
}
function cropImage(img, rect) {
  const ctx = new DrawContext();
  ctx.size = new Size(rect.width, rect.height);
  ctx.opaque = true;
  ctx.respectScreenScale = false;
  ctx.drawImageAtPoint(img, new Point(-rect.x, -rect.y));
  return ctx.getImage();
}
// Poor-man's gaussian: downscale then upscale.
function blurImage(img) {
  const w = img.size.width, h = img.size.height;
  const smallCtx = new DrawContext();
  const dw = Math.max(2, Math.round(w / 16));
  const dh = Math.max(2, Math.round(h / 16));
  smallCtx.size = new Size(dw, dh);
  smallCtx.opaque = true;
  smallCtx.respectScreenScale = false;
  smallCtx.drawImageInRect(img, new Rect(0, 0, dw, dh));
  const soft = smallCtx.getImage();
  const bigCtx = new DrawContext();
  bigCtx.size = new Size(w, h);
  bigCtx.opaque = true;
  bigCtx.respectScreenScale = false;
  bigCtx.drawImageInRect(soft, new Rect(0, 0, w, h));
  return bigCtx.getImage();
}
function tintImage(img, dark) {
  const ctx = new DrawContext();
  ctx.size = img.size;
  ctx.opaque = true;
  ctx.respectScreenScale = false;
  ctx.drawImageInRect(img, new Rect(0, 0, img.size.width, img.size.height));
  ctx.setFillColor(dark ? new Color("#101018", 0.32) : new Color("#FFFFFF", 0.25));
  ctx.fillRect(new Rect(0, 0, img.size.width, img.size.height));
  return ctx.getImage();
}
function backgroundImageFor(design, family, position) {
  if (design.background !== "glass" && design.background !== "clear") return null;
  const wall = loadWallpaper();
  if (!wall) return null;
  let rect;
  if (position) {
    rect = widgetRect(wall.size.width, wall.size.height, family, position);
  } else {
    const aspect = family === "medium" ? 2.14 : family === "large" ? 0.955 : 1;
    let w = wall.size.width * 0.86;
    let h = w / aspect;
    if (h > wall.size.height * 0.8) { h = wall.size.height * 0.8; w = h * aspect; }
    rect = new Rect((wall.size.width - w) / 2, (wall.size.height - h) / 2, w, h);
  }
  let img = cropImage(wall, rect);
  if (design.background === "glass") {
    img = blurImage(img);
    img = tintImage(img, (design.glassTint || "dark") !== "light");
  }
  return img;
}

function drawFreestyle(design, family, bgImg) {
  const sizes = { small: [474, 474], medium: [1014, 474], large: [1014, 1062] };
  const dims = sizes[family] || sizes.small;
  const W = dims[0], H = dims[1];
  const ctx = new DrawContext();
  ctx.size = new Size(W, H); ctx.opaque = false; ctx.respectScreenScale = false;
  if (bgImg) {
    ctx.drawImageInRect(bgImg, new Rect(0, 0, W, H));
  } else {
    const colors = themeColors(design);
    const c1 = hexToRgb(colors[0]); const c2 = hexToRgb(colors[1]);
    const steps = 60;
    const horizontal = design.gradientDir === "horizontal";
    for (let i = 0; i < steps; i++) {
      const t = i / (steps - 1);
      const mix = [0, 1, 2].map(function (j) { return c1[j] + (c2[j] - c1[j]) * t; });
      ctx.setFillColor(new Color(rgbToHex(mix)));
      if (horizontal) {
        ctx.fillRect(new Rect(Math.floor((W * i) / steps), 0, Math.ceil(W / steps) + 1, H));
      } else {
        ctx.fillRect(new Rect(0, Math.floor((H * i) / steps), W, Math.ceil(H / steps) + 1));
      }
    }
  }
  const scale = Math.min(W, H) / 158;
  const els = design.canvasElements || [];
  for (const el of els) {
    const px = el.x * W; const py = el.y * H; const fs = (el.size || 20) * scale;
    const op = (typeof el.opacity === "number" && el.opacity >= 0 && el.opacity <= 1) ? el.opacity : 1;
    if (el.kind === "shape") {
      const shapeType = el.shape || "rect";
      let wPx, hPx;
      if (shapeType === "circle") { wPx = hPx = (el.w || 0.5) * Math.min(W, H); }
      else { wPx = (el.w || 0.5) * W; hPx = (el.h || 0.25) * H; }
      const rect = new Rect(px - wPx / 2, py - hPx / 2, wPx, hPx);
      ctx.setFillColor(new Color(el.colorHex || "#FFFFFF", op));
      const path = new Path();
      if (shapeType === "circle") { path.addEllipse(rect); }
      else {
        const r = shapeType === "pill" ? Math.min(wPx, hPx) / 2 : 6 * scale;
        path.addRoundedRect(rect, r, r);
      }
      ctx.addPath(path);
      ctx.fillPath();
      continue;
    }
    let text;
    if (el.kind === "clock") { const df = new DateFormatter(); df.useShortTimeStyle(); text = df.string(new Date()); }
    else if (el.kind === "date") { const df = new DateFormatter(); df.dateFormat = "EEE MMM d"; text = df.string(new Date()); }
    else if (el.kind === "battery") { text = Math.round(Device.batteryLevel() * 100) + "%"; }
    else if (el.kind === "countdown") { text = String(Math.abs(daysUntil(el.dateISO))); }
    else if (el.kind === "symbol") { text = SYMBOL_EMOJI[el.symbolName] || "⭐"; }
    else { text = el.text || "Text"; }
    ctx.setFont(fontFor(design.fontStyle, fs, true));
    ctx.setTextColor(new Color(el.colorHex || "#FFFFFF", el.kind === "emoji" ? 1 : op));
    ctx.setTextAlignedCenter();
    ctx.drawTextInRect(text, new Rect(px - W / 2, py - fs * 0.72, W, fs * 1.7));
  }
  return ctx.getImage();
}
function hashString(s) {
  let h = 5381;
  for (let i = 0; i < s.length; i++) { h = ((h << 5) + h + s.charCodeAt(i)) >>> 0; }
  return h.toString(36);
}
async function loadIcon(url) {
  try {
    const fm = FileManager.local();
    const dir = fm.cacheDirectory();
    // Hash the FULL url — icon URLs share identical endings across apps, so
    // suffix-based names collide and serve the wrong app's icon.
    const name = "wk2_" + hashString(url) + "_" + url.length + ".png";
    const path = fm.joinPath(dir, name);
    if (fm.fileExists(path)) return fm.readImage(path);
    const img = await new Request(url).loadImage();
    fm.writeImage(path, img);
    return img;
  } catch (e) { return null; }
}
async function buildLauncher(w, design, family, tc, style) {
  const apps = (design.apps || []).slice(0, 12);
  if (apps.length === 0) { centeredText(w, "Add apps in the designer", fontFor(style, 13, true), tc); return; }
  const ls = design.launcherStyle || {};
  const iconPt = Math.min(Math.max(Number(ls.iconSize) || 30, 16), 120);
  const showLabels = ls.labels !== false;
  const radius = ls.shape === "circle" ? iconPt / 2 : Math.round(iconPt * 0.24);
  const columns = Math.min(Math.max(Math.round(Number(ls.columns) || 0), 0), 6);
  const perRow = columns > 0 ? columns : (family === "small" ? 2 : 4);
  const labelPt = Math.min(13, Math.max(9, Math.round(iconPt * 0.22)));
  if (family === "small" && apps[0].url && !w.url) w.url = apps[0].url;
  w.addSpacer();
  for (let i = 0; i < apps.length; i += perRow) {
    const row = w.addStack();
    row.layoutHorizontally();
    row.addSpacer();
    for (const app of apps.slice(i, i + perRow)) {
      const cell = row.addStack();
      cell.layoutVertically();
      cell.centerAlignContent();
      if (app.url) cell.url = app.url;
      const iconRow = cell.addStack();
      iconRow.layoutHorizontally();
      iconRow.addSpacer();
      let realIcon = null;
      if (app.iconUrl) realIcon = await loadIcon(app.iconUrl);
      if (realIcon) {
        const img = iconRow.addImage(realIcon);
        img.imageSize = new Size(iconPt, iconPt);
        img.cornerRadius = radius;
      } else {
        const icon = iconRow.addText(app.emoji || "🌐");
        icon.font = Font.systemFont(Math.round(iconPt * 0.9));
      }
      iconRow.addSpacer();
      if (showLabels) {
        const labelRow = cell.addStack();
        labelRow.layoutHorizontally();
        labelRow.addSpacer();
        const label = labelRow.addText(app.label || "App");
        label.font = fontFor(style, labelPt, false);
        label.textColor = tc;
        label.textOpacity = 0.85;
        label.lineLimit = 1;
        labelRow.addSpacer();
      }
      row.addSpacer();
    }
    if (i + perRow < apps.length) w.addSpacer(10);
  }
  w.addSpacer();
}
async function buildWidget(design, position) {
  const family = config.widgetFamily || "small";
  const w = new ListWidget();
  w.setPadding(12, 12, 12, 12);
  const bgImg = backgroundImageFor(design, family, position);
  if (bgImg && design.kind !== "freestyle") {
    w.backgroundImage = bgImg;
  } else if (!bgImg) {
    const colors = themeColors(design);
    const g = new LinearGradient();
    g.colors = [new Color(colors[0]), new Color(colors[1])];
    g.locations = [0, 1];
    g.startPoint = new Point(0, 0);
    g.endPoint = design.gradientDir === "vertical" ? new Point(0, 1)
      : design.gradientDir === "horizontal" ? new Point(1, 0) : new Point(1, 1);
    w.backgroundGradient = g;
  }
  const tc = new Color(design.textColorHex || "#FFFFFF");
  const style = design.fontStyle || "rounded";
  if (design.tapUrl) w.url = design.tapUrl;
  if (design.kind === "freestyle") {
    w.setPadding(0, 0, 0, 0);
    w.backgroundImage = drawFreestyle(design, family, bgImg);
    w.refreshAfterDate = new Date(Date.now() + 5 * 60 * 1000);
    return w;
  }
  if (design.kind === "launcher") {
    await buildLauncher(w, design, family, tc, style);
    return w;
  }
  w.addSpacer();
  switch (design.kind) {
    case "clock": {
      const t = w.addDate(new Date());
      t.applyTimeStyle(); t.font = fontFor(style, 40, true); t.textColor = tc;
      t.centerAlignText(); t.minimumScaleFactor = 0.4;
      const d = w.addDate(new Date());
      d.applyDateStyle(); d.font = fontFor(style, 12, false); d.textColor = tc;
      d.textOpacity = 0.85; d.centerAlignText();
      break;
    }
    case "date": {
      const now = new Date();
      const wd = new DateFormatter(); wd.dateFormat = "EEEE";
      const mo = new DateFormatter(); mo.dateFormat = "MMMM";
      centeredText(w, wd.string(now).toUpperCase(), fontFor(style, 13, true), tc).textOpacity = 0.85;
      centeredText(w, String(now.getDate()), fontFor(style, 50, true), tc);
      centeredText(w, mo.string(now), fontFor(style, 13, false), tc).textOpacity = 0.85;
      break;
    }
    case "countdown": {
      const days = daysUntil(design.targetDate);
      centeredText(w, design.primaryText || design.name || "Countdown", fontFor(style, 13, true), tc).textOpacity = 0.85;
      centeredText(w, String(Math.abs(days)), fontFor(style, 44, true), tc);
      centeredText(w, days >= 0 ? "days to go" : "days ago", fontFor(style, 11, false), tc).textOpacity = 0.75;
      break;
    }
    case "quote": {
      centeredText(w, "“", fontFor(style, 18, true), tc).textOpacity = 0.6;
      centeredText(w, design.primaryText || "Add a quote", fontFor(style, 15, true), tc);
      if (design.secondaryText) {
        centeredText(w, "— " + design.secondaryText, fontFor(style, 11, false), tc).textOpacity = 0.75;
      }
      break;
    }
    case "battery": {
      const level = Math.round(Device.batteryLevel() * 100);
      centeredText(w, "🔋", Font.systemFont(22), tc);
      centeredText(w, level + "%", fontFor(style, 40, true), tc);
      centeredText(w, Device.isCharging() ? "charging" : "battery", fontFor(style, 11, false), tc).textOpacity = 0.75;
      break;
    }
    default: {
      centeredText(w, design.primaryText || design.name || "WidgetKing", fontFor(style, 18, true), tc);
    }
  }
  w.addSpacer();
  w.refreshAfterDate = new Date(Date.now() + 5 * 60 * 1000);
  return w;
}
// Widget parameter: "Design Name" or "Design Name | position" where position
// aligns Clear/Glass wallpaper slices (small: top/middle/bottom-left/right;
// medium & large: top, middle, bottom).
const rawParameter = String(args.widgetParameter || "");
const paramParts = rawParameter.split("|");
const parameter = (paramParts[0] || "").trim().toLowerCase();
const widgetPosition = (paramParts[1] || "").trim().toLowerCase();

let runPreview = true;
if (config.runsInApp) {
  const prefs = loadPrefs();
  const labelsShown = prefs.iconLabels !== false;
  const menu = new Alert();
  menu.title = "WidgetKing";
  menu.message = "Glass and Clear widgets show your wallpaper. One-time setup: long-press the Home Screen, swipe to the last empty page, screenshot it — then pick that screenshot here.";
  menu.addAction("Preview a widget");
  menu.addAction("Set wallpaper photo…");
  menu.addAction("Icon labels on Home Screen: " + (labelsShown ? "Shown" : "Hidden"));
  menu.addCancelAction("Cancel");
  const choice = await menu.presentAlert();
  if (choice === 1) {
    runPreview = false;
    try {
      const img = await Photos.fromLibrary();
      FileManager.local().writeImage(wallpaperPath(), img);
      const done = new Alert();
      done.title = "Wallpaper saved ✓";
      done.message = "Glass and Clear widgets will now use it. For pixel-perfect Clear widgets, set each widget's Parameter to: Design Name | position (e.g. My Clock | top-left).";
      done.addAction("OK");
      await done.presentAlert();
    } catch (e) {}
  } else if (choice === 2) {
    runPreview = false;
    prefs.iconLabels = !labelsShown;
    savePrefs(prefs);
    const done = new Alert();
    done.title = "Alignment updated ✓";
    done.message = prefs.iconLabels === false
      ? "Clear widgets now align to the Large-icons Home Screen (labels hidden). Flip this back if you show labels again."
      : "Clear widgets now align to the standard Home Screen (labels shown under icons).";
    done.addAction("OK");
    await done.presentAlert();
  } else if (choice === -1) {
    runPreview = false;
  }
}

if (config.runsInWidget || runPreview) {
  let design = DESIGNS.find(function (d) { return (d.name || "").toLowerCase() === parameter; });
  if (!design) design = DESIGNS[0];
  if (!design) {
    const w = new ListWidget();
    w.addText("No designs yet — build one in the WidgetKing designer.");
    if (config.runsInWidget) { Script.setWidget(w); } else { await w.presentSmall(); }
  } else {
    const w = await buildWidget(design, widgetPosition);
    if (config.runsInWidget) { Script.setWidget(w); } else { await w.presentMedium(); }
  }
}
Script.complete();
