// WidgetKing — Scriptable renderer
// Paste this whole file into a new script in the free Scriptable app,
// then add a Scriptable widget to your Home Screen and pick this script.
// Set the widget's "Parameter" to a design name to choose which design
// it shows — every widget can point at a different design.
//
// The DESIGNS array below is normally generated by the WidgetKing web
// designer (web/index.html) — design there, tap "Copy Scriptable Script",
// and paste over this script.

const DESIGNS = [
  {
    "id": "sample-1",
    "name": "Clock",
    "kind": "clock",
    "themeID": "royal",
    "fontStyle": "rounded",
    "textColorHex": "#FFFFFF",
    "primaryText": "",
    "secondaryText": "",
    "targetDate": "",
    "canvasElements": []
  }
];

const THEMES = {
  midnight: ["#232526", "#414345"],
  royal: ["#5B2C98", "#8E44AD"],
  sunset: ["#FF512F", "#F09819"],
  ocean: ["#1A2980", "#26D0CE"],
  forest: ["#134E5E", "#71B280"],
  candy: ["#FC5C7D", "#6A82FB"],
  lava: ["#870000", "#190A05"],
  gold: ["#B8860B", "#FFD700"],
  berry: ["#8E2DE2", "#4A00E0"],
  mist: ["#606C88", "#3F4C6B"],
  mint: ["#02AABD", "#00CDAC"],
  paper: ["#F5F5F0", "#E4E0D8"]
};

const SYMBOL_EMOJI = {
  "star.fill": "⭐", "heart.fill": "❤️", "bolt.fill": "⚡",
  "moon.stars.fill": "🌙", "sun.max.fill": "☀️", "cloud.fill": "☁️",
  "leaf.fill": "🍃", "flame.fill": "🔥", "sparkles": "✨",
  "music.note": "🎵", "pawprint.fill": "🐾", "crown.fill": "👑"
};

function fontFor(style, size, bold) {
  if (style === "serif") return new Font(bold ? "Georgia-Bold" : "Georgia", size);
  if (style === "mono") return bold ? Font.boldMonospacedSystemFont(size) : Font.regularMonospacedSystemFont(size);
  if (style === "classic") return bold ? Font.boldSystemFont(size) : Font.systemFont(size);
  return bold ? Font.boldRoundedSystemFont(size) : Font.regularRoundedSystemFont(size);
}

function themeColors(design) {
  return THEMES[design.themeID] || THEMES.midnight;
}

function daysUntil(isoDate) {
  if (!isoDate) return 0;
  const parts = isoDate.split("-").map(Number);
  const target = new Date(parts[0], (parts[1] || 1) - 1, parts[2] || 1);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  return Math.round((target - today) / 86400000);
}

function centeredText(widget, str, font, color) {
  const t = widget.addText(str);
  t.font = font;
  t.textColor = color;
  t.centerAlignText();
  t.minimumScaleFactor = 0.5;
  return t;
}

function hexToRgb(hex) {
  const clean = hex.replace("#", "");
  return [
    parseInt(clean.substring(0, 2), 16),
    parseInt(clean.substring(2, 4), 16),
    parseInt(clean.substring(4, 6), 16)
  ];
}

function rgbToHex(rgb) {
  return "#" + rgb.map(function (v) {
    return Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0");
  }).join("");
}

function drawFreestyle(design, family) {
  const sizes = { small: [474, 474], medium: [1014, 474], large: [1014, 1062] };
  const dims = sizes[family] || sizes.small;
  const W = dims[0], H = dims[1];

  const ctx = new DrawContext();
  ctx.size = new Size(W, H);
  ctx.opaque = false;
  ctx.respectScreenScale = false;

  // Vertical gradient approximated with strips (DrawContext has no gradient API).
  const colors = themeColors(design);
  const c1 = hexToRgb(colors[0]);
  const c2 = hexToRgb(colors[1]);
  const steps = 60;
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    const mix = [0, 1, 2].map(function (j) { return c1[j] + (c2[j] - c1[j]) * t; });
    ctx.setFillColor(new Color(rgbToHex(mix)));
    ctx.fillRect(new Rect(0, Math.floor((H * i) / steps), W, Math.ceil(H / steps) + 1));
  }

  const scale = Math.min(W, H) / 158;
  const elements = design.canvasElements || [];
  for (const el of elements) {
    const px = el.x * W;
    const py = el.y * H;
    const fs = (el.size || 20) * scale;

    let text;
    if (el.kind === "clock") {
      const df = new DateFormatter();
      df.useShortTimeStyle();
      text = df.string(new Date());
    } else if (el.kind === "date") {
      const df = new DateFormatter();
      df.dateFormat = "EEE MMM d";
      text = df.string(new Date());
    } else if (el.kind === "symbol") {
      text = SYMBOL_EMOJI[el.symbolName] || "⭐";
    } else {
      text = el.text || "Text";
    }

    ctx.setFont(fontFor(design.fontStyle, fs, true));
    ctx.setTextColor(new Color(el.colorHex || "#FFFFFF"));
    ctx.setTextAlignedCenter();
    ctx.drawTextInRect(text, new Rect(px - W / 2, py - fs * 0.72, W, fs * 1.7));
  }

  return ctx.getImage();
}

function buildLauncher(w, design, family, tc, style) {
  const apps = (design.apps || []).slice(0, 12);
  if (apps.length === 0) { centeredText(w, "Add apps in the designer", fontFor(style, 13, true), tc); return; }
  const perRow = family === "small" ? 2 : 4;
  // iOS allows only one tap target on small widgets — the whole widget opens
  // the first app there; medium/large get per-icon tap targets.
  if (family === "small" && apps[0].url) w.url = apps[0].url;
  w.addSpacer();
  for (let i = 0; i < apps.length; i += perRow) {
    const row = w.addStack();
    row.layoutHorizontally();
    row.addSpacer();
    for (const app of apps.slice(i, i + perRow)) {
      const cell = row.addStack();
      cell.layoutVertically();
      cell.centerAlignContent();
      if (app.url) cell.url = app.url;
      const iconRow = cell.addStack();
      iconRow.layoutHorizontally();
      iconRow.addSpacer();
      const icon = iconRow.addText(app.emoji || "🌐");
      icon.font = Font.systemFont(family === "small" ? 26 : 30);
      iconRow.addSpacer();
      const labelRow = cell.addStack();
      labelRow.layoutHorizontally();
      labelRow.addSpacer();
      const label = labelRow.addText(app.label || "App");
      label.font = fontFor(style, 9, false);
      label.textColor = tc;
      label.textOpacity = 0.85;
      label.lineLimit = 1;
      labelRow.addSpacer();
      row.addSpacer();
    }
    if (i + perRow < apps.length) w.addSpacer(10);
  }
  w.addSpacer();
}

function buildWidget(design) {
  const family = config.widgetFamily || "small";
  const w = new ListWidget();
  w.setPadding(12, 12, 12, 12);

  const colors = themeColors(design);
  const gradient = new LinearGradient();
  gradient.colors = [new Color(colors[0]), new Color(colors[1])];
  gradient.locations = [0, 1];
  w.backgroundGradient = gradient;

  const tc = new Color(design.textColorHex || "#FFFFFF");
  const style = design.fontStyle || "rounded";

  if (design.kind === "freestyle") {
    w.setPadding(0, 0, 0, 0);
    w.backgroundImage = drawFreestyle(design, family);
    w.refreshAfterDate = new Date(Date.now() + 5 * 60 * 1000);
    return w;
  }

  if (design.kind === "launcher") {
    buildLauncher(w, design, family, tc, style);
    return w;
  }

  w.addSpacer();
  switch (design.kind) {
    case "clock": {
      const t = w.addDate(new Date());
      t.applyTimeStyle();
      t.font = fontFor(style, 40, true);
      t.textColor = tc;
      t.centerAlignText();
      t.minimumScaleFactor = 0.4;
      const d = w.addDate(new Date());
      d.applyDateStyle();
      d.font = fontFor(style, 12, false);
      d.textColor = tc;
      d.textOpacity = 0.85;
      d.centerAlignText();
      break;
    }
    case "date": {
      const now = new Date();
      const weekday = new DateFormatter();
      weekday.dateFormat = "EEEE";
      const month = new DateFormatter();
      month.dateFormat = "MMMM";
      centeredText(w, weekday.string(now).toUpperCase(), fontFor(style, 13, true), tc).textOpacity = 0.85;
      centeredText(w, String(now.getDate()), fontFor(style, 50, true), tc);
      centeredText(w, month.string(now), fontFor(style, 13, false), tc).textOpacity = 0.85;
      break;
    }
    case "countdown": {
      const days = daysUntil(design.targetDate);
      const title = design.primaryText || design.name || "Countdown";
      centeredText(w, title, fontFor(style, 13, true), tc).textOpacity = 0.85;
      centeredText(w, String(Math.abs(days)), fontFor(style, 44, true), tc);
      centeredText(w, days >= 0 ? "days to go" : "days ago", fontFor(style, 11, false), tc).textOpacity = 0.75;
      break;
    }
    case "quote": {
      centeredText(w, "“", fontFor(style, 18, true), tc).textOpacity = 0.6;
      centeredText(w, design.primaryText || "Add a quote", fontFor(style, 15, true), tc);
      if (design.secondaryText) {
        centeredText(w, "— " + design.secondaryText, fontFor(style, 11, false), tc).textOpacity = 0.75;
      }
      break;
    }
    case "battery": {
      const level = Math.round(Device.batteryLevel() * 100);
      centeredText(w, "🔋", Font.systemFont(22), tc);
      centeredText(w, level + "%", fontFor(style, 40, true), tc);
      centeredText(w, Device.isCharging() ? "charging" : "battery", fontFor(style, 11, false), tc).textOpacity = 0.75;
      break;
    }
    default: {
      centeredText(w, design.primaryText || design.name || "WidgetKing", fontFor(style, 18, true), tc);
    }
  }
  w.addSpacer();

  // iOS decides the real cadence; this asks for roughly 5-minute refreshes.
  w.refreshAfterDate = new Date(Date.now() + 5 * 60 * 1000);
  return w;
}

const parameter = (args.widgetParameter || "").trim().toLowerCase();
let design = DESIGNS.find(function (d) {
  return (d.name || "").toLowerCase() === parameter;
});
if (!design) design = DESIGNS[0];

if (!design) {
  const w = new ListWidget();
  w.addText("No designs yet — build one in the WidgetKing designer.");
  if (config.runsInWidget) { Script.setWidget(w); } else { await w.presentSmall(); }
} else {
  const w = buildWidget(design);
  if (config.runsInWidget) { Script.setWidget(w); } else { await w.presentSmall(); }
}
Script.complete();
