// WidgetKing — Scriptable renderer
// Paste this whole file into a new script in the free Scriptable app.
// This reference copy is generated from the web designer's embedded template
// (web/index.html) with a sample design; the designer's "Copy Scriptable
// Script" button produces the same code with YOUR designs embedded.
//
// Widget "Parameter": "Design Name" or "Design Name | position" (position
// aligns Glass/Clear wallpaper slices). Run the script inside Scriptable to
// set the wallpaper photo for Glass/Clear backgrounds, or to switch Clear
// alignment for the Large-icons (labels hidden) Home Screen.

// WidgetKing — Scriptable renderer (generated by the WidgetKing web designer)
// Widget "Parameter" = design name chooses which design a widget shows.

const DESIGNS = [
  {
    "id": "sample-1",
    "name": "Clock",
    "kind": "clock",
    "themeID": "royal",
    "fontStyle": "rounded",
    "textColorHex": "#FFFFFF",
    "primaryText": "",
    "secondaryText": "",
    "targetDate": "",
    "background": "gradient",
    "glassTint": "dark",
    "canvasElements": [],
    "apps": []
  }
];
const WK_VERSION = 44;

const THEMES = {
  midnight: ["#232526", "#414345"], royal: ["#5B2C98", "#8E44AD"],
  sunset: ["#FF512F", "#F09819"], ocean: ["#1A2980", "#26D0CE"],
  forest: ["#134E5E", "#71B280"], candy: ["#FC5C7D", "#6A82FB"],
  lava: ["#870000", "#190A05"], gold: ["#B8860B", "#FFD700"],
  berry: ["#8E2DE2", "#4A00E0"], mist: ["#606C88", "#3F4C6B"],
  mint: ["#02AABD", "#00CDAC"], paper: ["#F5F5F0", "#E4E0D8"],
  rosegold: ["#9F5F6F", "#E8B4B8"], lavender: ["#6D5BBA", "#B49FDC"],
  sage: ["#3E5C4A", "#A3C9A8"], blush: ["#B24592", "#F15F79"],
  mocha: ["#3E2723", "#8D6E63"], navy: ["#0F2027", "#2C5364"],
  aurora: ["#1D976C", "#59C9A5"], cosmos: ["#0F0C29", "#764BA2"]
};
const SYMBOL_EMOJI = {
  "star.fill": "⭐", "heart.fill": "❤️", "bolt.fill": "⚡",
  "moon.stars.fill": "🌙", "sun.max.fill": "☀️", "cloud.fill": "☁️",
  "leaf.fill": "🍃", "flame.fill": "🔥", "sparkles": "✨",
  "music.note": "🎵", "pawprint.fill": "🐾", "crown.fill": "👑"
};

// iOS built-in font names for each style id: [regular, bold].
const FONT_NAMES = {
  serif: ["Georgia", "Georgia-Bold"],
  avenir: ["AvenirNext-Regular", "AvenirNext-Bold"],
  futura: ["Futura-Medium", "Futura-Bold"],
  didot: ["Didot", "Didot-Bold"],
  baskerville: ["Baskerville", "Baskerville-Bold"],
  typewriter: ["AmericanTypewriter", "AmericanTypewriter-Bold"],
  marker: ["MarkerFelt-Thin", "MarkerFelt-Wide"],
  chalkboard: ["ChalkboardSE-Regular", "ChalkboardSE-Bold"],
  noteworthy: ["Noteworthy-Light", "Noteworthy-Bold"],
  script: ["SnellRoundhand", "SnellRoundhand-Bold"],
  copperplate: ["Copperplate", "Copperplate-Bold"],
  optima: ["Optima-Regular", "Optima-Bold"],
  palatino: ["Palatino-Roman", "Palatino-Bold"]
};
function fontFor(style, size, bold) {
  const names = FONT_NAMES[style];
  if (names) {
    try { return new Font(bold ? names[1] : names[0], size); } catch (e) {}
  }
  if (style === "mono") return bold ? Font.boldMonospacedSystemFont(size) : Font.regularMonospacedSystemFont(size);
  if (style === "classic") return bold ? Font.boldSystemFont(size) : Font.systemFont(size);
  return bold ? Font.boldRoundedSystemFont(size) : Font.regularRoundedSystemFont(size);
}
function themeColors(d) {
  if (d.themeID === "custom" && d.customColors && d.customColors.length === 2) return d.customColors;
  return THEMES[d.themeID] || THEMES.midnight;
}
function dayOfYear(d) {
  const start = new Date(d.getFullYear(), 0, 0);
  return Math.floor((d - start) / 86400000);
}
// Quote widgets rotate daily when the quote field holds one entry per line.
function activeQuote(design) {
  const lines = String(design.primaryText || "").split("\n").map(function (s) { return s.trim(); }).filter(Boolean);
  if (lines.length <= 1) return design.primaryText || "";
  return lines[dayOfYear(new Date()) % lines.length];
}
function weatherEmoji(code) {
  if (code === 0) return "☀️";
  if (code <= 2) return "🌤";
  if (code === 3) return "☁️";
  if (code === 45 || code === 48) return "🌫";
  if (code >= 51 && code <= 67) return "🌧";
  if (code >= 71 && code <= 77) return "❄️";
  if (code >= 80 && code <= 82) return "🌧";
  if (code >= 85 && code <= 86) return "❄️";
  if (code >= 95) return "⛈";
  return "🌡";
}
// Free weather from Open-Meteo (no API key). Location and result are cached
// so widget refreshes stay fast and work offline with the last reading.
async function fetchWeather() {
  const fm = FileManager.local();
  const cachePath = fm.joinPath(fm.documentsDirectory(), "widgetking-weather.json");
  try {
    if (fm.fileExists(cachePath)) {
      const cached = JSON.parse(fm.readString(cachePath));
      if (cached && (Date.now() - cached.at) < 30 * 60 * 1000) return cached;
    }
  } catch (e) {}
  try {
    const prefs = loadPrefs();
    let lat = prefs.lat, lon = prefs.lon;
    if (typeof lat !== "number" || typeof lon !== "number") {
      Location.setAccuracyToKilometer();
      const loc = await Location.current();
      lat = loc.latitude; lon = loc.longitude;
      prefs.lat = lat; prefs.lon = lon;
      savePrefs(prefs);
    }
    const url = "https://api.open-meteo.com/v1/forecast?latitude=" + lat + "&longitude=" + lon +
      "&current=temperature_2m,weather_code&temperature_unit=fahrenheit";
    const data = await new Request(url).loadJSON();
    const out = { at: Date.now(), tempF: Math.round(data.current.temperature_2m), code: data.current.weather_code };
    fm.writeString(cachePath, JSON.stringify(out));
    return out;
  } catch (e) {
    try { if (fm.fileExists(cachePath)) return JSON.parse(fm.readString(cachePath)); } catch (e2) {}
    return null;
  }
}
function weatherText(el, wx) {
  if (!wx) return "--°";
  let temp = wx.tempF;
  if (el.unit === "c") temp = Math.round((wx.tempF - 32) * 5 / 9);
  return weatherEmoji(wx.code) + " " + temp + "°";
}
// Upcoming calendar events (asks for calendar permission on first run).
// Gathers today through next week, including all-day events like birthdays.
async function fetchUpcomingEvents(count) {
  try {
    const now = new Date();
    let events = [];
    try { events = events.concat(await CalendarEvent.today([])); } catch (e) {}
    try { events = events.concat(await CalendarEvent.tomorrow([])); } catch (e) {}
    try { events = events.concat(await CalendarEvent.thisWeek([])); } catch (e) {}
    try { events = events.concat(await CalendarEvent.nextWeek([])); } catch (e) {}
    const seen = {};
    events = events.filter(function (e) {
      if (!e || !e.endDate || e.endDate <= now) return false;
      const k = e.identifier || (String(e.title) + e.startDate);
      if (seen[k]) return false;
      seen[k] = true;
      return true;
    }).sort(function (a, b) { return a.startDate - b.startDate; });
    const df = new DateFormatter();
    df.useShortTimeStyle();
    const out = [];
    for (const e of events.slice(0, count)) {
      let title = String(e.title || "Event");
      if (title.length > 20) title = title.slice(0, 19) + "…";
      const dayDiff = Math.round(
        (new Date(e.startDate.getFullYear(), e.startDate.getMonth(), e.startDate.getDate()) -
         new Date(now.getFullYear(), now.getMonth(), now.getDate())) / 86400000);
      const when = dayDiff <= 0 ? (e.isAllDay ? "today" : df.string(e.startDate))
        : dayDiff === 1 ? "tomorrow" : "in " + dayDiff + "d";
      out.push({ title: title, when: when });
    }
    return out;
  } catch (e) { return null; }
}
function calendarText(el, events) {
  if (!events) return "Calendar off";
  if (events.length === 0) return "No events ✓";
  const n = Math.min(Math.max(Number(el.count) || 1, 1), 4);
  return events.slice(0, n).map(function (e) { return e.title + " · " + e.when; }).join("\n");
}
// Live Sleeper fantasy matchup (public API, no login) — cached 20 min per
// league so widget refreshes stay fast and the last score shows offline.
async function fetchSleeper(el) {
  if (!el.leagueID || !el.userID) return null;
  const fm = FileManager.local();
  const cachePath = fm.joinPath(fm.documentsDirectory(), "widgetking-sleeper-" + el.leagueID + ".json");
  try {
    if (fm.fileExists(cachePath)) {
      const cached = JSON.parse(fm.readString(cachePath));
      if (cached && (Date.now() - cached.at) < 20 * 60 * 1000) return cached;
    }
  } catch (e) {}
  try {
    const base = "https://api.sleeper.app/v1";
    const state = await new Request(base + "/state/nfl").loadJSON();
    const week = Math.max(1, Number(state.display_week || state.week) || 1);
    const rosters = await new Request(base + "/league/" + el.leagueID + "/rosters").loadJSON();
    const mine = rosters.find(function (r) { return r.owner_id === el.userID; });
    if (!mine) return null;
    const users = await new Request(base + "/league/" + el.leagueID + "/users").loadJSON();
    function teamOf(ownerID) {
      const u = (users || []).find(function (x) { return x.user_id === ownerID; }) || {};
      const meta = u.metadata || {};
      let avatar = meta.avatar || "";
      if (!avatar && u.avatar) avatar = "https://sleepercdn.com/avatars/thumbs/" + u.avatar;
      return { name: String(meta.team_name || u.display_name || "Team").slice(0, 18), avatar: avatar };
    }
    const sorted = rosters.slice().sort(function (a, b) {
      const aw = (a.settings || {}).wins || 0, bw = (b.settings || {}).wins || 0;
      if (bw !== aw) return bw - aw;
      return ((b.settings || {}).fpts || 0) - ((a.settings || {}).fpts || 0);
    });
    const rank = sorted.indexOf(mine) + 1;
    const out = {
      at: Date.now(),
      wins: (mine.settings || {}).wins || 0,
      losses: (mine.settings || {}).losses || 0,
      rank: rank,
      me: 0, opp: 0,
      myTeam: teamOf(el.userID),
      oppTeam: { name: "Opponent", avatar: "" }
    };
    const matchups = await new Request(base + "/league/" + el.leagueID + "/matchups/" + week).loadJSON();
    const my = (matchups || []).find(function (m) { return m.roster_id === mine.roster_id; });
    if (my) {
      out.me = Math.round((my.points || 0) * 10) / 10;
      const opp = (matchups || []).find(function (m) {
        return m.matchup_id === my.matchup_id && m.roster_id !== my.roster_id;
      });
      if (opp) {
        out.opp = Math.round((opp.points || 0) * 10) / 10;
        const oppRoster = rosters.find(function (r) { return r.roster_id === opp.roster_id; });
        if (oppRoster) out.oppTeam = teamOf(oppRoster.owner_id);
      }
    }
    fm.writeString(cachePath, JSON.stringify(out));
    return out;
  } catch (e) {
    try { if (fm.fileExists(cachePath)) return JSON.parse(fm.readString(cachePath)); } catch (e2) {}
    return null;
  }
}
function sleeperText(el, s) {
  if (!s) {
    if (el.mode === "record") return "– · –";
    if (el.mode === "myteam") return "My Team";
    if (el.mode === "opponent") return "Opponent";
    return "Connect Sleeper";
  }
  if (el.mode === "record") return s.wins + "-" + s.losses + (s.rank ? " · #" + s.rank : "");
  if (el.mode === "myteam") return (s.myTeam || {}).name || "My Team";
  if (el.mode === "opponent") return (s.oppTeam || {}).name || "Opponent";
  return s.me.toFixed(1) + " – " + s.opp.toFixed(1);
}
// Fetch only the live data this design actually uses.
async function liveDataFor(design) {
  const els = design.canvasElements || [];
  const live = {};
  if (els.some(function (e) { return e.kind === "weather"; })) live.weather = await fetchWeather();
  const calEls = els.filter(function (e) { return e.kind === "calendar"; });
  if (calEls.length) {
    const maxCount = Math.max.apply(null, calEls.map(function (e) { return Math.min(Math.max(Number(e.count) || 1, 1), 4); }));
    live.events = await fetchUpcomingEvents(maxCount);
  }
  const sleeperEls = els.filter(function (e) { return (e.kind === "sleeper" || e.kind === "sleeperlogo") && e.leagueID; });
  if (sleeperEls.length) {
    live.sleeper = {};
    for (const el of sleeperEls) {
      if (!live.sleeper[el.leagueID]) live.sleeper[el.leagueID] = await fetchSleeper(el);
    }
  }
  return live;
}
function progressPct(el) {
  const src = el.source || "day";
  const now = new Date();
  if (src === "battery") { try { return Device.batteryLevel(); } catch (e) { return 0.5; } }
  if (src === "year") {
    const start = new Date(now.getFullYear(), 0, 1);
    const end = new Date(now.getFullYear() + 1, 0, 1);
    return (now - start) / (end - start);
  }
  if (src === "countdown") {
    const done = Math.max(0, -daysUntil(el.startISO || el.dateISO));
    const left = Math.max(0, daysUntil(el.dateISO));
    const span = done + left;
    return span > 0 ? done / span : 1;
  }
  return (now.getHours() * 3600 + now.getMinutes() * 60 + now.getSeconds()) / 86400;
}
function daysUntil(iso) {
  if (!iso) return 0;
  const p = iso.split("-").map(Number);
  const target = new Date(p[0], (p[1] || 1) - 1, p[2] || 1);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  return Math.round((target - today) / 86400000);
}
function centeredText(w, str, font, color) {
  const t = w.addText(str);
  t.font = font; t.textColor = color; t.centerAlignText(); t.minimumScaleFactor = 0.5;
  return t;
}
function hexToRgb(hex) {
  const c = hex.replace("#", "");
  return [parseInt(c.substring(0,2),16), parseInt(c.substring(2,4),16), parseInt(c.substring(4,6),16)];
}
function rgbToHex(rgb) {
  return "#" + rgb.map(function (v) {
    return Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0");
  }).join("");
}

// ---- Transparent / glass backgrounds (wallpaper slice technique) ----
function wallpaperPath() {
  const fm = FileManager.local();
  return fm.joinPath(fm.documentsDirectory(), "widgetking-wallpaper.jpg");
}
function loadWallpaper() {
  try {
    const fm = FileManager.local();
    const path = wallpaperPath();
    if (fm.fileExists(path)) return fm.readImage(path);
  } catch (e) {}
  return null;
}
// Exact widget frames per iPhone, measured by the Scriptable community
// (mzeryck's Widget Blur data), keyed by the screenshot's pixel height.
// Each frame: [small, medium, large, left, right, top, middle, bottom].
// "labels" = normal Home Screen; "nolabels" = iOS Large-icons mode (labels
// hidden), which shifts the whole grid — toggle it in the in-app menu.
const SCREEN_FRAMES = {
  "2868": { labels: [510, 1092, 1146, 114, 696, 276, 912, 1548], nolabels: [530, 1138, 1136, 91, 699, 276, 882, 1488] },
  "2796": { labels: [510, 1092, 1146, 98, 681, 252, 888, 1524], nolabels: [530, 1139, 1136, 75, 684, 252, 858, 1464] },
  "2622": { labels: [486, 1032, 1098, 87, 633, 261, 872, 1485], nolabels: [495, 1037, 1035, 84, 626, 270, 810, 1350] },
  "2556": { labels: [474, 1017, 1062, 81, 624, 240, 828, 1416], nolabels: [495, 1047, 1047, 66, 618, 243, 795, 1347] },
  "2778": { labels: [510, 1092, 1146, 96, 678, 246, 882, 1518] },
  "2688": { labels: [507, 1080, 1137, 81, 654, 228, 858, 1488] },
  "2532": { labels: [474, 1014, 1062, 78, 618, 231, 819, 1407] },
  "2436": { labels: [465, 987, 1035, 69, 591, 213, 783, 1353] },
  "2079": { labels: [423, 875, 933, 42, 494, 186, 696, 1206] },
  "1792": { labels: [338, 720, 758, 55, 437, 159, 579, 999] },
  "1624": { labels: [310, 658, 690, 46, 394, 142, 522, 902] },
  "1334": { labels: [296, 642, 648, 54, 400, 60, 412, 764], nolabels: [309, 667, 667, 41, 399, 67, 425, 783] },
  "2208": { labels: [471, 1044, 1071, 99, 672, 114, 696, 1278] },
  "2001": { labels: [444, 963, 972, 81, 600, 90, 618, 1146] },
  "1136": { labels: [282, 584, 622, 30, 332, 59, 399, 399] }
};
// Named models for the in-app picker (screen-height key -> label).
const DEVICE_MODELS = [
  ["2868", "iPhone 17 Pro Max / 16 Pro Max"],
  ["2622", "iPhone 17 Pro / 17 / 16 Pro"],
  ["2796", "iPhone 16 Plus / 15 Pro Max / 15 Plus / 14 Pro Max"],
  ["2556", "iPhone 16e / 16 / 15 / 15 Pro / 14 Pro"],
  ["2532", "iPhone 14 / 13 / 13 Pro / 12 / 12 Pro"],
  ["2436", "iPhone 13 mini / 12 mini / 11 Pro / XS / X"],
  ["1334", "iPhone SE (2nd/3rd gen)"]
];
function prefsPath() {
  const fm = FileManager.local();
  return fm.joinPath(fm.documentsDirectory(), "widgetking-prefs.json");
}
function loadPrefs() {
  try {
    const fm = FileManager.local();
    if (fm.fileExists(prefsPath())) return JSON.parse(fm.readString(prefsPath())) || {};
  } catch (e) {}
  return {};
}
function savePrefs(prefs) {
  try { FileManager.local().writeString(prefsPath(), JSON.stringify(prefs)); } catch (e) {}
}
// True widget dimensions in points for THIS device, derived from the
// measured pixel frames (frame px / screen scale). Assuming a generic size
// makes iOS stretch the layout — the spacing then looks nothing like the
// designer preview.
// Which frame table applies to THIS iPhone: the user's explicit model pick
// beats auto-detection from the hardware.
function frameEntryKey() {
  const prefs = loadPrefs();
  if (prefs.screenKey && SCREEN_FRAMES[String(prefs.screenKey)]) return String(prefs.screenKey);
  try {
    const hPx = Math.round(Math.max(Device.screenSize().width, Device.screenSize().height) * Device.screenScale());
    if (SCREEN_FRAMES[String(hPx)]) return String(hPx);
  } catch (e) {}
  return "";
}
function widgetPointSizes(family) {
  try {
    const scale = Device.screenScale();
    const entry = SCREEN_FRAMES[frameEntryKey()];
    if (entry) {
      const f = (loadPrefs().iconLabels === false && entry.nolabels) ? entry.nolabels : entry.labels;
      const small = f[0] / scale, med = f[1] / scale, large = f[2] / scale;
      if (family === "medium") return [med, small];
      if (family === "large") return [med, large];
      return [small, small];
    }
  } catch (e) {}
  const PT = { small: [155, 155], medium: [329, 155], large: [329, 345] };
  return PT[family] || PT.small;
}
function widgetRect(imgW, imgH, family, position) {
  const pos = position || (family === "small" ? "top-left" : "top");
  const posParts = pos.split("-");
  const row = posParts[0] || "top";
  const side = posParts[1] || "left";
  // Identify the device first (model pick / hardware), not the screenshot:
  // resized or iCloud-optimized screenshots must not land in the wrong row.
  let key = frameEntryKey();
  if (!key && SCREEN_FRAMES[String(Math.round(imgH))]) key = String(Math.round(imgH));
  const entry = SCREEN_FRAMES[key];
  let x, y, w, h, rows;
  if (entry) {
    const raw = (loadPrefs().iconLabels === false && entry.nolabels) ? entry.nolabels : entry.labels;
    // If the saved image was scaled down, scale the frame with it.
    const sc = imgH / Number(key);
    const f = raw.map(function (v) { return v * sc; });
    rows = { top: f[5], middle: f[6], bottom: f[7] };
    x = f[3];
    w = h = f[0];
    if (family === "small") {
      x = side === "right" ? f[4] : f[3];
    } else if (family === "medium") {
      w = f[1];
    } else if (family === "large") {
      w = f[1]; h = f[2];
    }
  } else {
    // Unknown screenshot size (e.g. a scaled photo) — proportional fallback.
    const sw = Math.round(imgW * 0.402);
    const gap = Math.round((imgW - 2 * sw) / 3);
    const rowStep = sw + gap;
    const top = Math.round(imgH * 0.0965);
    rows = { top: top, middle: top + rowStep, bottom: top + 2 * rowStep };
    x = gap;
    w = h = sw;
    if (family === "small") {
      x = side === "right" ? gap * 2 + sw : gap;
    } else if (family === "medium") {
      w = imgW - 2 * gap;
    } else if (family === "large") {
      w = imgW - 2 * gap; h = sw * 2 + gap;
    }
  }
  y = rows[row] != null ? rows[row] : rows.top;
  if (family === "large" && row === "bottom") y = rows.middle;
  // User-tuned fine alignment from the in-app "Nudge" menu.
  const prefs = loadPrefs();
  y += Number(prefs.offsetY) || 0;
  x += Number(prefs.offsetX) || 0;
  x = Math.min(Math.max(0, x), Math.max(0, imgW - w));
  if (y + h > imgH) y = Math.max(0, imgH - h);
  if (y < 0) y = 0;
  return new Rect(x, y, w, h);
}
function cropImage(img, rect) {
  const ctx = new DrawContext();
  ctx.size = new Size(rect.width, rect.height);
  ctx.opaque = true;
  ctx.respectScreenScale = false;
  ctx.drawImageAtPoint(img, new Point(-rect.x, -rect.y));
  return ctx.getImage();
}
// Poor-man's gaussian: downscale then upscale.
function blurImage(img) {
  const w = img.size.width, h = img.size.height;
  const smallCtx = new DrawContext();
  const dw = Math.max(2, Math.round(w / 16));
  const dh = Math.max(2, Math.round(h / 16));
  smallCtx.size = new Size(dw, dh);
  smallCtx.opaque = true;
  smallCtx.respectScreenScale = false;
  smallCtx.drawImageInRect(img, new Rect(0, 0, dw, dh));
  const soft = smallCtx.getImage();
  const bigCtx = new DrawContext();
  bigCtx.size = new Size(w, h);
  bigCtx.opaque = true;
  bigCtx.respectScreenScale = false;
  bigCtx.drawImageInRect(soft, new Rect(0, 0, w, h));
  return bigCtx.getImage();
}
function tintImage(img, dark, strength) {
  const s = (typeof strength === "number" && strength >= 0.1 && strength <= 1) ? strength : 1;
  const ctx = new DrawContext();
  ctx.size = img.size;
  ctx.opaque = true;
  ctx.respectScreenScale = false;
  ctx.drawImageInRect(img, new Rect(0, 0, img.size.width, img.size.height));
  ctx.setFillColor(dark ? new Color("#101018", 0.32 * s) : new Color("#FFFFFF", 0.25 * s));
  ctx.fillRect(new Rect(0, 0, img.size.width, img.size.height));
  return ctx.getImage();
}
// Paints the design's gradient at partial opacity over a wallpaper slice —
// the "see-through gradient" background. Strips must not overlap or the
// seams double-blend into visible lines.
function gradientOver(img, design, alpha) {
  const w = img.size.width, h = img.size.height;
  const ctx = new DrawContext();
  ctx.size = img.size;
  ctx.opaque = true;
  ctx.respectScreenScale = false;
  ctx.drawImageInRect(img, new Rect(0, 0, w, h));
  const colors = themeColors(design);
  const c1 = hexToRgb(colors[0]); const c2 = hexToRgb(colors[1]);
  const steps = 60;
  const horizontal = design.gradientDir === "horizontal";
  const span = horizontal ? w : h;
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    const mix = [0, 1, 2].map(function (j) { return c1[j] + (c2[j] - c1[j]) * t; });
    ctx.setFillColor(new Color(rgbToHex(mix), alpha));
    const a = Math.floor((span * i) / steps);
    const b = Math.floor((span * (i + 1)) / steps);
    if (horizontal) { ctx.fillRect(new Rect(a, 0, b - a, h)); }
    else { ctx.fillRect(new Rect(0, a, w, b - a)); }
  }
  return ctx.getImage();
}
function bgOpacityOf(design) {
  const op = Number(design.bgOpacity);
  return (isFinite(op) && op >= 0.1 && op < 1) ? op : 1;
}
function backgroundImageFor(design, family, position) {
  const op = bgOpacityOf(design);
  const glassy = design.background === "glass" || design.background === "clear";
  const blend = design.background === "gradient" && op < 1;
  if (!glassy && !blend) return null;
  const wall = loadWallpaper();
  if (!wall) return null;
  let rect;
  if (position || design.background === "clear") {
    // Clear must always slice a real widget frame — without a position it
    // assumes the top spot (set "Name | position" in the Parameter to fix).
    rect = widgetRect(wall.size.width, wall.size.height, family, position);
  } else {
    const aspect = family === "medium" ? 2.14 : family === "large" ? 0.955 : 1;
    let w = wall.size.width * 0.86;
    let h = w / aspect;
    if (h > wall.size.height * 0.8) { h = wall.size.height * 0.8; w = h * aspect; }
    rect = new Rect((wall.size.width - w) / 2, (wall.size.height - h) / 2, w, h);
  }
  let img = cropImage(wall, rect);
  if (design.background === "glass") {
    img = blurImage(img);
    img = tintImage(img, (design.glassTint || "dark") !== "light", op);
  } else if (blend) {
    img = gradientOver(img, design, op);
  }
  return img;
}

function drawFreestyle(design, family, bgImg, live) {
  // Draw at the device's true widget size (in pixels) so nothing stretches.
  const pts = widgetPointSizes(family);
  let s = 3;
  try { s = Device.screenScale() || 3; } catch (e) {}
  const W = Math.round(pts[0] * s), H = Math.round(pts[1] * s);
  const ctx = new DrawContext();
  ctx.size = new Size(W, H); ctx.opaque = false; ctx.respectScreenScale = false;
  if (bgImg) {
    ctx.drawImageInRect(bgImg, new Rect(0, 0, W, H));
  } else {
    const colors = themeColors(design);
    const c1 = hexToRgb(colors[0]); const c2 = hexToRgb(colors[1]);
    const steps = 60;
    const horizontal = design.gradientDir === "horizontal";
    for (let i = 0; i < steps; i++) {
      const t = i / (steps - 1);
      const mix = [0, 1, 2].map(function (j) { return c1[j] + (c2[j] - c1[j]) * t; });
      ctx.setFillColor(new Color(rgbToHex(mix)));
      if (horizontal) {
        ctx.fillRect(new Rect(Math.floor((W * i) / steps), 0, Math.ceil(W / steps) + 1, H));
      } else {
        ctx.fillRect(new Rect(0, Math.floor((H * i) / steps), W, Math.ceil(H / steps) + 1));
      }
    }
  }
  const scale = Math.min(W, H) / 158;
  const els = design.canvasElements || [];
  for (const el of els) {
    const px = el.x * W; const py = el.y * H; const fs = (el.size || 20) * scale;
    const op = (typeof el.opacity === "number" && el.opacity >= 0 && el.opacity <= 1) ? el.opacity : 1;
    if (el.kind === "shape") {
      const shapeType = el.shape || "rect";
      let wPx, hPx;
      if (shapeType === "circle") { wPx = hPx = (el.w || 0.5) * Math.min(W, H); }
      else { wPx = (el.w || 0.5) * W; hPx = (el.h || 0.25) * H; }
      const rect = new Rect(px - wPx / 2, py - hPx / 2, wPx, hPx);
      const rr2 = shapeType === "pill" ? Math.min(wPx, hPx) / 2
        : (typeof el.radius === "number" ? el.radius * scale : 6 * scale);
      if (op > 0.02) {
        ctx.setFillColor(new Color(el.colorHex || "#FFFFFF", op));
        const path = new Path();
        if (shapeType === "circle") { path.addEllipse(rect); }
        else { path.addRoundedRect(rect, rr2, rr2); }
        ctx.addPath(path);
        ctx.fillPath();
      }
      const bw = (Number(el.border) || 0) * scale;
      if (bw > 0) {
        ctx.setStrokeColor(new Color(el.borderHex || el.colorHex || "#FFFFFF", 1));
        ctx.setLineWidth(bw);
        const inset = bw / 2;
        const srect = new Rect(rect.x + inset, rect.y + inset, rect.width - bw, rect.height - bw);
        const spath = new Path();
        if (shapeType === "circle") { spath.addEllipse(srect); }
        else { spath.addRoundedRect(srect, Math.max(0, rr2 - inset), Math.max(0, rr2 - inset)); }
        ctx.addPath(spath);
        ctx.strokePath();
      }
      continue;
    }
    if (el.kind === "photo") {
      // Photos arrive pre-baked from the designer: crop shape and opacity are
      // already burned into the PNG's pixels/alpha, so we just draw it.
      // Multiple photos rotate daily or on every widget refresh.
      const list = (Array.isArray(el.b64s) && el.b64s.length) ? el.b64s : (el.b64 ? [el.b64] : []);
      if (list.length) {
        let idx = 0;
        if (list.length > 1) {
          idx = el.rotate === "refresh"
            ? Math.floor(Math.random() * list.length)
            : dayOfYear(new Date()) % list.length;
        }
        try {
          const img = Image.fromData(Data.fromBase64String(list[idx]));
          let wPx, hPx;
          if (el.shape === "circle") { wPx = hPx = (el.w || 0.55) * Math.min(W, H); }
          else { wPx = (el.w || 0.55) * W; hPx = wPx * (el.aspect || 1); }
          ctx.drawImageInRect(img, new Rect(px - wPx / 2, py - hPx / 2, wPx, hPx));
        } catch (e) {}
      } else {
        // No image data made it into the script (photos don't travel in sync
        // links) — say so on the widget instead of leaving a silent hole.
        ctx.setFont(Font.mediumSystemFont(9));
        ctx.setTextColor(new Color("#FFFFFF", 0.55));
        ctx.setTextAlignedCenter();
        ctx.drawTextInRect("photo missing - re-add in designer", new Rect(px - 70, py - 6, 140, 14));
      }
      continue;
    }
    if (el.kind === "art") {
      // Pre-baked in the designer (curved/rotated text, gradients) — just draw.
      if (el.b64 && el.artW) {
        try {
          const img = Image.fromData(Data.fromBase64String(el.b64));
          const wPx = el.artW * scale, hPx = (el.artH || el.artW) * scale;
          ctx.drawImageInRect(img, new Rect(px - wPx / 2, py - hPx / 2, wPx, hPx));
        } catch (e) {}
      } else {
        ctx.setFont(Font.mediumSystemFont(9));
        ctx.setTextColor(new Color("#FFFFFF", 0.55));
        ctx.drawTextInRect("art missing - re-copy the script", new Rect(px - 70, py - 6, 140, 14));
      }
      continue;
    }
    if (el.kind === "progress") {
      const pct = Math.min(Math.max(progressPct(el), 0), 1);
      const wPx = (el.w || 0.7) * W;
      const hPx = Math.max(3 * scale, (el.size || 8) * scale);
      const x0 = px - wPx / 2, y0 = py - hPx / 2;
      const r = hPx / 2;
      ctx.setFillColor(new Color(el.colorHex || "#FFFFFF", op * 0.25));
      const track = new Path();
      track.addRoundedRect(new Rect(x0, y0, wPx, hPx), r, r);
      ctx.addPath(track);
      ctx.fillPath();
      if (pct > 0.02) {
        ctx.setFillColor(new Color(el.colorHex || "#FFFFFF", op));
        const fill = new Path();
        fill.addRoundedRect(new Rect(x0, y0, Math.max(hPx, wPx * pct), hPx), r, r);
        ctx.addPath(fill);
        ctx.fillPath();
      }
      continue;
    }
    if (el.kind === "ring") {
      // Progress ring: polyline arc (DrawContext has no arc API). Track
      // circle at low alpha, then the progress sweep from 12 o'clock.
      const pct = Math.min(Math.max(progressPct(el), 0), 1);
      const dia = (el.w || 0.55) * Math.min(W, H);
      const radius2 = dia / 2;
      const stroke = Math.max(2 * scale, (el.size || 7) * scale);
      const rr = radius2 - stroke / 2;
      ctx.setLineWidth(stroke);
      function ringPath(fromT, toT) {
        const path = new Path();
        const steps = Math.max(8, Math.round(72 * (toT - fromT)));
        for (let s2 = 0; s2 <= steps; s2++) {
          const a = -Math.PI / 2 + 2 * Math.PI * (fromT + (toT - fromT) * (s2 / steps));
          const ptx = px + rr * Math.cos(a);
          const pty = py + rr * Math.sin(a);
          if (s2 === 0) path.move(new Point(ptx, pty)); else path.addLine(new Point(ptx, pty));
        }
        return path;
      }
      ctx.setStrokeColor(new Color(el.colorHex || "#FFFFFF", op * 0.25));
      ctx.addPath(ringPath(0, 1));
      ctx.strokePath();
      if (pct > 0.01) {
        ctx.setStrokeColor(new Color(el.colorHex || "#FFFFFF", op));
        ctx.addPath(ringPath(0, pct));
        ctx.strokePath();
      }
      continue;
    }
    if (el.kind === "month") {
      // Mini month calendar: weekday header + date grid, today circled.
      const fsM = (el.size || 9) * scale;
      const gw = (el.w || 0.6) * W;
      const cell = gw / 7;
      const now2 = new Date();
      const first = new Date(now2.getFullYear(), now2.getMonth(), 1);
      const startDow = first.getDay();
      const daysIn = new Date(now2.getFullYear(), now2.getMonth() + 1, 0).getDate();
      const rows = Math.ceil((startDow + daysIn) / 7);
      const rowH = fsM * 1.7;
      const gh = rowH * (rows + 1);
      const x0 = px - gw / 2, y0 = py - gh / 2;
      const headers = ["S", "M", "T", "W", "T", "F", "S"];
      ctx.setTextAlignedCenter();
      ctx.setFont(fontFor(el.font || design.fontStyle, fsM * 0.9, true));
      ctx.setTextColor(new Color(el.colorHex || "#FFFFFF", op * 0.6));
      for (let c = 0; c < 7; c++) {
        ctx.drawTextInRect(headers[c], new Rect(x0 + c * cell, y0, cell, rowH));
      }
      const prevDays = new Date(now2.getFullYear(), now2.getMonth(), 0).getDate();
      ctx.setFont(fontFor(el.font || design.fontStyle, fsM, false));
      ctx.setTextColor(new Color(el.colorHex || "#FFFFFF", op * 0.3));
      for (let b = 0; b < startDow; b++) {
        ctx.drawTextInRect(String(prevDays - startDow + 1 + b),
          new Rect(x0 + b * cell, y0 + rowH + (rowH - fsM * 1.4) / 2, cell, fsM * 1.4));
      }
      const tail = rows * 7 - (startDow + daysIn);
      for (let a = 0; a < tail; a++) {
        const idx2 = startDow + daysIn + a;
        ctx.drawTextInRect(String(a + 1),
          new Rect(x0 + (idx2 % 7) * cell, y0 + (Math.floor(idx2 / 7) + 1) * rowH + (rowH - fsM * 1.4) / 2, cell, fsM * 1.4));
      }
      for (let d = 1; d <= daysIn; d++) {
        const idx = startDow + d - 1;
        const r = Math.floor(idx / 7), c = idx % 7;
        const cx2 = x0 + c * cell, cy2 = y0 + (r + 1) * rowH;
        if (d === now2.getDate()) {
          ctx.setFillColor(new Color(el.accentHex || "#4A90F6", op));
          const dia = Math.min(cell, rowH) * 0.95;
          ctx.fillEllipse(new Rect(cx2 + (cell - dia) / 2, cy2 + (rowH - dia) / 2, dia, dia));
          ctx.setFont(fontFor(el.font || design.fontStyle, fsM, true));
          ctx.setTextColor(new Color("#FFFFFF", 1));
        } else {
          ctx.setFont(fontFor(el.font || design.fontStyle, fsM, false));
          ctx.setTextColor(new Color(el.colorHex || "#FFFFFF", op * 0.9));
        }
        ctx.drawTextInRect(String(d), new Rect(cx2, cy2 + (rowH - fsM * 1.4) / 2, cell, fsM * 1.4));
      }
      continue;
    }
    if (el.kind === "app" || el.kind === "sleeperlogo") continue; // rendered as overlay stacks
    let text;
    if (el.kind === "clock") { const df = new DateFormatter(); df.useShortTimeStyle(); text = df.string(new Date()); }
    else if (el.kind === "date") { const df = new DateFormatter(); df.dateFormat = "EEE MMM d"; text = df.string(new Date()); }
    else if (el.kind === "battery") { text = Math.round(Device.batteryLevel() * 100) + "%"; }
    else if (el.kind === "countdown") { text = String(Math.abs(daysUntil(el.dateISO))); }
    else if (el.kind === "symbol") { text = SYMBOL_EMOJI[el.symbolName] || "⭐"; }
    else if (el.kind === "icon") { text = el.text || "★"; }
    else if (el.kind === "weather") { text = weatherText(el, live ? live.weather : null); }
    else if (el.kind === "calendar") { text = calendarText(el, live ? live.events : null); }
    else if (el.kind === "sleeper") { text = sleeperText(el, live && live.sleeper ? live.sleeper[el.leagueID] : null); }
    else { text = el.text || "Text"; }
    // multi:"day" — a text element holding several lines shows one per day.
    if (el.kind === "text" && el.multi === "day" && text.indexOf("\n") >= 0) {
      const qlines = text.split("\n").map(function (s) { return s.trim(); }).filter(Boolean);
      if (qlines.length) text = qlines[dayOfYear(new Date()) % qlines.length];
    }
    const isBold = el.kind !== "text" || el.bold !== false;
    ctx.setFont(fontFor(el.font || design.fontStyle, fs, isBold));
    ctx.setTextColor(new Color(el.colorHex || "#FFFFFF", el.kind === "emoji" ? 1 : op));
    if (el.kind === "text" && el.w > 0) {
      // Text box: fixed width, wraps, top-anchored — mirrors the designer.
      if (el.align === "left") { ctx.setTextAlignedLeft(); }
      else if (el.align === "right") { ctx.setTextAlignedRight(); }
      else { ctx.setTextAlignedCenter(); }
      const boxW = el.w * W;
      ctx.drawTextInRect(text, new Rect(px - boxW / 2, py - fs * 0.72, boxW, H));
    } else {
      ctx.setTextAlignedCenter();
      const lines = el.kind === "calendar" ? Math.min(Math.max(Number(el.count) || 1, 1), 4) : 1;
      ctx.drawTextInRect(text, new Rect(px - W / 2, py - fs * 0.72, W, fs * 1.7 * lines));
    }
  }
  return ctx.getImage();
}
// App elements in freestyle designs are laid over the drawn background as
// real stacks, so they get crisp rounded icons AND per-icon tap targets
// (iOS allows multiple tap targets on medium/large widgets only).
async function addFreestyleApps(w, design, family, live) {
  const apps = (design.canvasElements || []).filter(function (el) { return el.kind === "app" || el.kind === "sleeperlogo"; });
  if (apps.length === 0) return;
  const dims = widgetPointSizes(family);
  const W = dims[0], H = dims[1];
  if (!w.url && apps[0].url) w.url = apps[0].url;
  // Group into rows: elements whose vertical centers overlap share a row.
  const sorted = apps.slice().sort(function (a, b) { return a.y - b.y; });
  const rows = [];
  for (const el of sorted) {
    const pt = Math.min(Math.max(Number(el.size) || 40, 16), 120);
    const top = el.y * H - pt / 2;
    const last = rows[rows.length - 1];
    if (last && top < last.bottom) {
      last.items.push(el);
      last.bottom = Math.max(last.bottom, top + pt + (el.showLabel ? 13 : 0));
    } else {
      rows.push({ top: Math.max(0, top), bottom: top + pt + (el.showLabel ? 13 : 0), items: [el] });
    }
  }
  const root = w.addStack();
  root.layoutVertically();
  root.size = new Size(W, H);
  let cursorY = 0;
  for (const row of rows) {
    if (row.top > cursorY) root.addSpacer(row.top - cursorY);
    const rowStack = root.addStack();
    rowStack.layoutHorizontally();
    rowStack.topAlignContent();
    let cursorX = 0;
    row.items.sort(function (a, b) { return a.x - b.x; });
    for (const el of row.items) {
      const pt = Math.min(Math.max(Number(el.size) || 40, 16), 120);
      const left = Math.max(0, el.x * W - pt / 2);
      if (left > cursorX) rowStack.addSpacer(left - cursorX);
      const cell = rowStack.addStack();
      cell.layoutVertically();
      if (el.url) cell.url = el.url;
      const iconStack = cell.addStack();
      if (el.kind === "sleeperlogo") {
        // Live Sleeper team avatar as a circular badge; taps open Sleeper.
        const s = live && live.sleeper ? live.sleeper[el.leagueID] : null;
        const team = s ? (el.side === "opp" ? s.oppTeam : s.myTeam) : null;
        let avatar = null;
        if (team && team.avatar) avatar = await loadIcon(team.avatar);
        if (avatar) {
          const img = iconStack.addImage(avatar);
          img.imageSize = new Size(pt, pt);
          img.cornerRadius = pt / 2;
        } else {
          const t = iconStack.addText(el.side === "opp" ? "🛡" : "🏈");
          t.font = Font.systemFont(Math.round(pt * 0.85));
        }
        if (!cell.url) cell.url = "sleeper://";
        cursorX = left + pt;
        continue;
      }
      const elTheme = el.iconTheme && ICON_THEMES[el.iconTheme] ? el.iconTheme : "real";
      let realIcon = null;
      if (elTheme !== "real") {
        const tile = iconStack.addImage(themedIconTile(el, elTheme, apps.indexOf(el), pt));
        tile.imageSize = new Size(pt, pt);
      } else {
        if (el.iconUrl) realIcon = await loadIcon(el.iconUrl);
        if (realIcon) {
          const img = iconStack.addImage(realIcon);
          img.imageSize = new Size(pt, pt);
          img.cornerRadius = el.shape === "circle" ? pt / 2 : Math.round(pt * 0.24);
        } else {
          const t = iconStack.addText(el.emoji || "📲");
          t.font = Font.systemFont(Math.round(pt * 0.9));
        }
      }
      if (el.showLabel) {
        const labelStack = cell.addStack();
        labelStack.layoutHorizontally();
        labelStack.addSpacer();
        const label = labelStack.addText(el.label || "App");
        label.font = fontFor(design.fontStyle, 9, false);
        label.textColor = new Color(design.textColorHex || "#FFFFFF");
        label.textOpacity = 0.85;
        label.lineLimit = 1;
        labelStack.addSpacer();
      }
      cursorX = left + pt;
    }
    rowStack.addSpacer();
    cursorY = row.bottom;
  }
  root.addSpacer();
}
function hashString(s) {
  let h = 5381;
  for (let i = 0; i < s.length; i++) { h = ((h << 5) + h + s.charCodeAt(i)) >>> 0; }
  return h.toString(36);
}
// Themed launcher icon tiles, drawn locally (no network): colored rounded
// square + the app's emoji or first letter. Must match ICON_THEMES in the
// designer so the preview and the widget agree.
const ICON_THEMES = {
  pastel: { colors: ["#FADCE4", "#DCEBFA", "#E8DFF5", "#FDEFD8", "#DFF5E8"], glyph: "#6B5B7A", line: false },
  line:   { colors: ["#FBFAF7"], glyph: "#33303B", line: true },
  noir:   { colors: ["#111116"], glyph: "#F2F2F5", line: false },
  zen:    { colors: ["#DDE5D6", "#E9E4D8", "#CDD9CE"], glyph: "#4A5A4E", line: false },
  neon:   { colors: ["#14002E"], glyph: "#00F0FF", line: false, glyphCycle: ["#FF2079", "#00F0FF", "#39FF14", "#FFD300"] }
};
function iconGlyph(app) {
  if (app.emoji && app.emoji !== "📱" && app.emoji !== "🌐" && app.emoji !== "📲") return app.emoji;
  return (app.label || "A").trim().charAt(0).toUpperCase();
}
function themedIconTile(app, themeName, index, pt) {
  const theme = ICON_THEMES[themeName];
  const S = Math.round(pt * 3);
  const ctx = new DrawContext();
  ctx.size = new Size(S, S);
  ctx.opaque = false;
  ctx.respectScreenScale = false;
  const r = Math.round(S * 0.24);
  const rect = new Rect(0, 0, S, S);
  const bg = theme.colors[index % theme.colors.length];
  const path = new Path();
  path.addRoundedRect(rect, r, r);
  ctx.addPath(path);
  ctx.setFillColor(new Color(bg));
  ctx.fillPath();
  if (theme.line) {
    const inset = Math.max(2, Math.round(S * 0.035));
    const inner = new Path();
    inner.addRoundedRect(new Rect(inset, inset, S - 2 * inset, S - 2 * inset), r - inset, r - inset);
    ctx.addPath(inner);
    ctx.setStrokeColor(new Color(theme.glyph));
    ctx.setLineWidth(Math.max(2, Math.round(S * 0.03)));
    ctx.strokePath();
  }
  const glyph = iconGlyph(app);
  const glyphColor = theme.glyphCycle ? theme.glyphCycle[index % theme.glyphCycle.length] : theme.glyph;
  ctx.setTextColor(new Color(glyphColor));
  ctx.setFont(Font.boldSystemFont(Math.round(S * 0.42)));
  ctx.setTextAlignedCenter();
  ctx.drawTextInRect(glyph, new Rect(0, S * 0.22, S, S * 0.62));
  return ctx.getImage();
}
async function loadIcon(url) {
  try {
    const fm = FileManager.local();
    const dir = fm.cacheDirectory();
    // Hash the FULL url — icon URLs share identical endings across apps, so
    // suffix-based names collide and serve the wrong app's icon.
    const name = "wk2_" + hashString(url) + "_" + url.length + ".png";
    const path = fm.joinPath(dir, name);
    if (fm.fileExists(path)) return fm.readImage(path);
    const img = await new Request(url).loadImage();
    fm.writeImage(path, img);
    return img;
  } catch (e) { return null; }
}
async function buildLauncher(w, design, family, tc, style) {
  const apps = (design.apps || []).slice(0, 12);
  if (apps.length === 0) { centeredText(w, "Add apps in the designer", fontFor(style, 13, true), tc); return; }
  const ls = design.launcherStyle || {};
  const iconPt = Math.min(Math.max(Number(ls.iconSize) || 30, 16), 120);
  const showLabels = ls.labels !== false;
  const radius = ls.shape === "circle" ? iconPt / 2 : Math.round(iconPt * 0.24);
  const columns = Math.min(Math.max(Math.round(Number(ls.columns) || 0), 0), 6);
  const perRow = columns > 0 ? columns : (family === "small" ? 2 : 4);
  const labelPt = Math.min(13, Math.max(9, Math.round(iconPt * 0.22)));
  // Whole-widget fallback URL: a tap on empty space (or anywhere on a Small
  // widget) opens the first app instead of bouncing into Scriptable.
  if (apps[0].url && !w.url) w.url = apps[0].url;
  // Deterministic layout: every margin and gap is a computed fixed number of
  // points — the same math the designer preview uses — because flexible
  // spacers distribute differently across iOS versions (preview mismatch).
  const dims = widgetPointSizes(family);
  const W = dims[0], H = dims[1];
  const pad = 12;
  const rowGap = 10;
  w.setPadding(0, 0, 0, 0);
  const root = w.addStack();
  root.layoutVertically();
  root.size = new Size(W, H);
  const cellH = iconPt + (showLabels ? labelPt + 3 : 0);
  const rowCount = Math.ceil(apps.length / perRow);
  const contentH = rowCount * cellH + (rowCount - 1) * rowGap;
  root.addSpacer(Math.max(0, (H - contentH) / 2));
  for (let i = 0; i < apps.length; i += perRow) {
    if (i > 0) root.addSpacer(rowGap);
    const rowApps = apps.slice(i, i + perRow);
    const n = rowApps.length;
    const gap = Math.max(0, (W - 2 * pad - n * iconPt) / (n + 1));
    const rowStack = root.addStack();
    rowStack.layoutHorizontally();
    rowStack.topAlignContent();
    rowStack.size = new Size(W, cellH);
    rowStack.addSpacer(pad + gap);
    for (let j = 0; j < n; j++) {
      const app = rowApps[j];
      if (j > 0) rowStack.addSpacer(gap);
      const cell = rowStack.addStack();
      cell.layoutVertically();
      cell.centerAlignContent();
      cell.size = new Size(iconPt, cellH);
      if (app.url) cell.url = app.url;
      const iconTheme = ls.iconTheme && ICON_THEMES[ls.iconTheme] ? ls.iconTheme : "real";
      let realIcon = null;
      if (iconTheme !== "real") {
        const tile = cell.addImage(themedIconTile(app, iconTheme, i + j, iconPt));
        tile.imageSize = new Size(iconPt, iconPt);
      } else {
        if (app.iconUrl) realIcon = await loadIcon(app.iconUrl);
        if (realIcon) {
          const img = cell.addImage(realIcon);
          img.imageSize = new Size(iconPt, iconPt);
          img.cornerRadius = radius;
        } else {
          const icon = cell.addText(app.emoji || "🌐");
          icon.font = Font.systemFont(Math.round(iconPt * 0.9));
          icon.centerAlignText();
        }
      }
      if (showLabels) {
        cell.addSpacer(3);
        const label = cell.addText(app.label || "App");
        label.font = fontFor(style, labelPt, false);
        label.textColor = tc;
        label.textOpacity = 0.85;
        label.lineLimit = 1;
        label.minimumScaleFactor = 0.6;
        label.centerAlignText();
      }
    }
    rowStack.addSpacer(pad + gap);
  }
  root.addSpacer(Math.max(0, (H - contentH) / 2));
}
async function buildWidget(design, position) {
  const family = config.widgetFamily || "small";
  const w = new ListWidget();
  w.setPadding(12, 12, 12, 12);
  const bgImg = backgroundImageFor(design, family, position);
  if (bgImg && design.kind !== "freestyle") {
    w.backgroundImage = bgImg;
  } else if (!bgImg) {
    const colors = themeColors(design);
    const g = new LinearGradient();
    g.colors = [new Color(colors[0]), new Color(colors[1])];
    g.locations = [0, 1];
    g.startPoint = new Point(0, 0);
    g.endPoint = design.gradientDir === "vertical" ? new Point(0, 1)
      : design.gradientDir === "horizontal" ? new Point(1, 0) : new Point(1, 1);
    w.backgroundGradient = g;
  }
  const tc = new Color(design.textColorHex || "#FFFFFF");
  const style = design.fontStyle || "rounded";
  if (design.tapUrl) w.url = design.tapUrl;
  if (design.kind === "freestyle") {
    w.setPadding(0, 0, 0, 0);
    const live = await liveDataFor(design);
    w.backgroundImage = drawFreestyle(design, family, bgImg, live);
    await addFreestyleApps(w, design, family, live);
    w.refreshAfterDate = new Date(Date.now() + 5 * 60 * 1000);
    return w;
  }
  if (design.kind === "launcher") {
    await buildLauncher(w, design, family, tc, style);
    return w;
  }
  w.addSpacer();
  switch (design.kind) {
    case "clock": {
      const t = w.addDate(new Date());
      t.applyTimeStyle(); t.font = fontFor(style, 40, true); t.textColor = tc;
      t.centerAlignText(); t.minimumScaleFactor = 0.4;
      const d = w.addDate(new Date());
      d.applyDateStyle(); d.font = fontFor(style, 12, false); d.textColor = tc;
      d.textOpacity = 0.85; d.centerAlignText();
      break;
    }
    case "date": {
      const now = new Date();
      const wd = new DateFormatter(); wd.dateFormat = "EEEE";
      const mo = new DateFormatter(); mo.dateFormat = "MMMM";
      centeredText(w, wd.string(now).toUpperCase(), fontFor(style, 13, true), tc).textOpacity = 0.85;
      centeredText(w, String(now.getDate()), fontFor(style, 50, true), tc);
      centeredText(w, mo.string(now), fontFor(style, 13, false), tc).textOpacity = 0.85;
      break;
    }
    case "countdown": {
      const days = daysUntil(design.targetDate);
      centeredText(w, design.primaryText || design.name || "Countdown", fontFor(style, 13, true), tc).textOpacity = 0.85;
      centeredText(w, String(Math.abs(days)), fontFor(style, 44, true), tc);
      centeredText(w, days >= 0 ? "days to go" : "days ago", fontFor(style, 11, false), tc).textOpacity = 0.75;
      break;
    }
    case "quote": {
      centeredText(w, "“", fontFor(style, 18, true), tc).textOpacity = 0.6;
      centeredText(w, activeQuote(design) || "Add a quote", fontFor(style, 15, true), tc);
      if (design.secondaryText) {
        centeredText(w, "— " + design.secondaryText, fontFor(style, 11, false), tc).textOpacity = 0.75;
      }
      break;
    }
    case "battery": {
      const level = Math.round(Device.batteryLevel() * 100);
      centeredText(w, "🔋", Font.systemFont(22), tc);
      centeredText(w, level + "%", fontFor(style, 40, true), tc);
      centeredText(w, Device.isCharging() ? "charging" : "battery", fontFor(style, 11, false), tc).textOpacity = 0.75;
      break;
    }
    default: {
      centeredText(w, design.primaryText || design.name || "WidgetKing", fontFor(style, 18, true), tc);
    }
  }
  w.addSpacer();
  w.refreshAfterDate = new Date(Date.now() + 5 * 60 * 1000);
  return w;
}
// Widget parameter: "Design Name" or "Design Name | position" where position
// aligns Clear/Glass wallpaper slices (small: top/middle/bottom-left/right;
// medium & large: top, middle, bottom).
const rawParameter = String(args.widgetParameter || "");
const paramParts = rawParameter.split("|");
const parameter = (paramParts[0] || "").trim().toLowerCase();
const widgetPosition = (paramParts[1] || "").trim().toLowerCase();

let runPreview = true;
if (config.runsInApp) {
  const prefs = loadPrefs();
  const labelsShown = prefs.iconLabels !== false;
  const menu = new Alert();
  menu.title = "WidgetKing · script v" + WK_VERSION;
  menu.message = "Glass and Clear widgets show your wallpaper. One-time setup: long-press the Home Screen, swipe to the last empty page, screenshot it — then pick that screenshot here.";
  menu.addAction("Preview a widget");
  menu.addAction("Set wallpaper photo…");
  menu.addAction("Nudge Clear alignment…");
  menu.addAction("Icon labels on Home Screen: " + (labelsShown ? "Shown" : "Hidden"));
  const pickedModel = DEVICE_MODELS.find(function (m) { return m[0] === String(prefs.screenKey || ""); });
  menu.addAction("iPhone model: " + (pickedModel ? pickedModel[1].split(" / ")[0] : "Auto-detect"));
  menu.addAction("Set up app shortcuts…");
  menu.addCancelAction("Cancel");
  const choice = await menu.presentAlert();
  if (choice === 1) {
    runPreview = false;
    try {
      const img = await Photos.fromLibrary();
      FileManager.local().writeImage(wallpaperPath(), img);
      const done = new Alert();
      done.title = "Wallpaper saved ✓";
      // A photo that isn't a true screenshot of THIS iPhone is the #1 cause
      // of misaligned/off-color Clear widgets — catch it right away.
      const expW = Math.round(Device.screenSize().width * Device.screenScale());
      const expH = Math.round(Device.screenSize().height * Device.screenScale());
      if (Math.round(img.size.width) !== expW || Math.round(img.size.height) !== expH) {
        done.title = "Saved — but check this ⚠️";
        done.message = "That image is " + Math.round(img.size.width) + "x" + Math.round(img.size.height) +
          ", but a screenshot of this iPhone is " + expW + "x" + expH +
          ". For perfect Clear widgets: swipe to an empty Home Screen page, take a fresh screenshot, and pick THAT (not the original photo — iOS shades the wallpaper, so the screenshot matches what's really on screen).";
      } else {
        done.message = "Glass and Clear widgets will now use it. For pixel-perfect Clear widgets, set each widget's Parameter to: Design Name | position (e.g. My Clock | top-left). If it's a touch off, use Nudge Clear alignment in this menu.";
      }
      done.addAction("OK");
      await done.presentAlert();
    } catch (e) {}
  } else if (choice === 2) {
    runPreview = false;
    const nudge = new Alert();
    nudge.title = "Nudge Clear alignment";
    nudge.message = "Shifts which wallpaper slice Clear/Glass widgets show. Current: " +
      (Number(prefs.offsetY) || 0) + "px vertical, " + (Number(prefs.offsetX) || 0) + "px horizontal.";
    nudge.addAction("⬆︎ Move picture up 10");
    nudge.addAction("⬆︎ Move picture up 30");
    nudge.addAction("⬇︎ Move picture down 10");
    nudge.addAction("⬇︎ Move picture down 30");
    nudge.addAction("⬅︎ Move picture left 10");
    nudge.addAction("⬅︎ Move picture left 30");
    nudge.addAction("➡︎ Move picture right 10");
    nudge.addAction("➡︎ Move picture right 30");
    nudge.addAction("Reset to 0");
    nudge.addCancelAction("Cancel");
    const pick = await nudge.presentAlert();
    if (pick >= 0) {
      // Moving the picture up means sampling a lower slice (+y), and so on.
      if (pick === 0) prefs.offsetY = (Number(prefs.offsetY) || 0) + 10;
      if (pick === 1) prefs.offsetY = (Number(prefs.offsetY) || 0) + 30;
      if (pick === 2) prefs.offsetY = (Number(prefs.offsetY) || 0) - 10;
      if (pick === 3) prefs.offsetY = (Number(prefs.offsetY) || 0) - 30;
      if (pick === 4) prefs.offsetX = (Number(prefs.offsetX) || 0) + 10;
      if (pick === 5) prefs.offsetX = (Number(prefs.offsetX) || 0) + 30;
      if (pick === 6) prefs.offsetX = (Number(prefs.offsetX) || 0) - 10;
      if (pick === 7) prefs.offsetX = (Number(prefs.offsetX) || 0) - 30;
      if (pick === 8) { prefs.offsetY = 0; prefs.offsetX = 0; }
      savePrefs(prefs);
      const done = new Alert();
      done.title = "Alignment nudged ✓";
      done.message = "Now " + (Number(prefs.offsetY) || 0) + "px vertical, " + (Number(prefs.offsetX) || 0) +
        "px horizontal. Widgets update within a few minutes (or tap Preview a widget to check now).";
      done.addAction("OK");
      await done.presentAlert();
    }
  } else if (choice === 3) {
    runPreview = false;
    prefs.iconLabels = !labelsShown;
    savePrefs(prefs);
    const done = new Alert();
    done.title = "Alignment updated ✓";
    done.message = prefs.iconLabels === false
      ? "Clear widgets now align to the Large-icons Home Screen (labels hidden). Flip this back if you show labels again."
      : "Clear widgets now align to the standard Home Screen (labels shown under icons).";
    done.addAction("OK");
    await done.presentAlert();
  } else if (choice === 4) {
    runPreview = false;
    const dm = new Alert();
    dm.title = "Which iPhone is this?";
    let detected = "";
    try {
      detected = Math.round(Device.screenSize().width * Device.screenScale()) + " x " +
        Math.round(Device.screenSize().height * Device.screenScale()) + " px";
    } catch (e) {}
    dm.message = "Clear/Glass alignment uses measured frames for your exact model. Auto-detect reads the hardware" +
      (detected ? " (this phone reports " + detected + ")" : "") + " — pick a model only if Auto looks wrong.";
    dm.addAction("Auto-detect (recommended)");
    for (const m of DEVICE_MODELS) dm.addAction(m[1]);
    dm.addCancelAction("Cancel");
    const dmPick = await dm.presentAlert();
    if (dmPick === 0) { delete prefs.screenKey; savePrefs(prefs); }
    else if (dmPick > 0) { prefs.screenKey = DEVICE_MODELS[dmPick - 1][0]; savePrefs(prefs); }
    if (dmPick >= 0) {
      const done = new Alert();
      done.title = "Alignment updated ✓";
      done.message = "Clear/Glass widgets now align using " +
        (dmPick === 0 ? "auto-detection" : DEVICE_MODELS[dmPick - 1][1]) +
        ". Widgets refresh within a few minutes.";
      done.addAction("OK");
      await done.presentAlert();
    }
  } else if (choice === 5) {
    runPreview = false;
    // Scan every embedded widget for app buttons that rely on a Shortcut,
    // then hand each one to the Shortcuts app with the exact name copied.
    // (Apple does not allow any app to create Shortcuts programmatically.)
    const names = [];
    for (const design of DESIGNS) {
      const apps = (design.apps || []).concat(
        (design.canvasElements || []).filter(function (e) { return e.kind === "app"; })
      );
      for (const app of apps) {
        const url = app.url || "";
        if (url.indexOf("shortcuts://run-shortcut") === 0) {
          let name = "Open " + (app.label || "App");
          const m = url.match(/name=([^&]+)/);
          if (m) { try { name = decodeURIComponent(m[1]); } catch (e) {} }
          if (names.indexOf(name) < 0) names.push(name);
        }
      }
    }
    if (names.length === 0) {
      const ok = new Alert();
      ok.title = "Nothing to set up 🎉";
      ok.message = "Every app button in your widgets opens directly — no Shortcuts needed.";
      ok.addAction("OK");
      await ok.presentAlert();
    } else {
      const list = new Alert();
      list.title = "Create these Shortcuts (" + names.length + ")";
      list.message = "Pick one — its exact name is copied and Shortcuts opens on a new shortcut. Add the action 'Open App', choose the app, then tap the title and rename it by pasting. Run this again for the next one.";
      for (const n of names) list.addAction(n);
      list.addCancelAction("Done");
      const idx = await list.presentSheet();
      if (idx >= 0) {
        Pasteboard.copyString(names[idx]);
        Safari.open("shortcuts://create-shortcut");
      }
    }
  } else if (choice === -1) {
    runPreview = false;
  }
}

if (config.runsInWidget || runPreview) {
  let design = DESIGNS.find(function (d) { return (d.name || "").toLowerCase() === parameter; });
  if (!design && parameter) {
    // Never fall back silently to another design — a wrong Parameter used to
    // render DESIGNS[0], which looked like a broken/blank widget.
    design = { name: "Not found", kind: "note", themeID: "midnight", fontStyle: "rounded",
      textColorHex: "#FFFFFF", background: "gradient", canvasElements: [], apps: [],
      primaryText: "No design called “" + (paramParts[0] || "").trim() +
        "” in this script.\nRe-copy the script from the designer (it must contain this design), or fix this widget's Parameter." };
  }
  if (!design) design = DESIGNS[0];
  if (!design) {
    const w = new ListWidget();
    w.addText("No designs yet — build one in the WidgetKing designer.");
    if (config.runsInWidget) { Script.setWidget(w); } else { await w.presentSmall(); }
  } else {
    const w = await buildWidget(design, widgetPosition);
    if (config.runsInWidget) { Script.setWidget(w); } else { await w.presentMedium(); }
  }
}
Script.complete();
