// Pull the template's data tables out of web/index.html by evaluating just
// those const blocks, then emit Shared/WKData.swift. Parity by construction.
import { readFileSync, writeFileSync } from 'fs';
const html = readFileSync('web/index.html', 'utf8');
const tpl = html.match(/<script type="text\/plain" id="scriptableTemplate">\n?([\s\S]*?)<\/script>/)[1];
function block(name) {
  const i = tpl.indexOf('const ' + name + ' = ');
  if (i < 0) throw new Error('missing ' + name);
  let depth = 0, j = i, started = false;
  for (; j < tpl.length; j++) {
    const ch = tpl[j];
    if (ch === '{' || ch === '[') { depth++; started = true; }
    else if (ch === '}' || ch === ']') { depth--; if (started && depth === 0) { j++; break; } }
  }
  return tpl.slice(i, j) + ';';
}
const src = ['THEMES', 'SYMBOL_EMOJI', 'FONT_NAMES', 'ICON_THEMES', 'VGLYPHS', 'VGLYPH_FOR'].map(block).join('\n');
const fn = new Function(src + '\nreturn { THEMES, SYMBOL_EMOJI, FONT_NAMES, ICON_THEMES, VGLYPHS, VGLYPH_FOR };');
const D = fn();
function vglyphPoints(stroke) {
  const first = stroke[0];
  if (Array.isArray(first) && (first[0] === 'c' || first[0] === 'a')) {
    const cx = first[1], cy = first[2], r = first[3];
    const a0 = first[0] === 'c' ? 0 : first[4];
    const a1 = first[0] === 'c' ? Math.PI * 2 : first[5];
    const n = Math.max(10, Math.round(20 * Math.abs(a1 - a0) / Math.PI));
    const pts = [];
    for (let i = 0; i <= n; i++) { const a = a0 + (a1 - a0) * (i / n); pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]); }
    return { pts, tiny: first[0] === 'c' && first[3] < 0.035 };
  }
  return { pts: stroke, tiny: false };
}
const q = s => JSON.stringify(String(s));
const r4 = v => Math.round(v * 10000) / 10000;
let out = '// GENERATED by tools/gen_wkdata.mjs from the Scriptable template in web/index.html.\n';
out += '// Do not edit by hand — regenerate so native and Scriptable never drift.\n';
out += 'import Foundation\n\n';
out += 'struct WKIconTheme {\n';
out += '    var colors: [String]; var glyph: String; var line = false; var glyphCycle: [String]? = nil\n';
out += '    var duo: [String]? = nil; var frost = false; var lineCycle = false; var lettersOnly = false\n';
out += '    var radius: Double = 0.24; var emojiTile = false; var neu = false; var glyphStyle = ""\n';
out += '    var gradStroke: [String]? = nil; var dots = false; var wordTile = false; var wordColors: [String]? = nil\n';
out += '    var wordStyle = ""; var glow = false; var thick = false; var ring = false\n';
out += '}\n\n';
out += 'struct WKGlyphStroke { var points: [[Double]]; var tinyCircle: Bool }\n\n';
out += 'enum WKData {\n';
out += '    static let themes: [String: [String]] = [\n' + Object.entries(D.THEMES).map(([k, v]) => `        ${q(k)}: [${v.map(q).join(', ')}],`).join('\n') + '\n    ]\n';
out += '    static let symbolEmoji: [String: String] = [\n' + Object.entries(D.SYMBOL_EMOJI).map(([k, v]) => `        ${q(k)}: ${q(v)},`).join('\n') + '\n    ]\n';
out += '    static let fontNames: [String: [String]] = [\n' + Object.entries(D.FONT_NAMES).map(([k, v]) => `        ${q(k)}: [${v.map(q).join(', ')}],`).join('\n') + '\n    ]\n';
out += '    static let iconThemes: [String: WKIconTheme] = [\n';
for (const [k, t] of Object.entries(D.ICON_THEMES)) {
  const parts = [`colors: [${t.colors.map(q).join(', ')}]`, `glyph: ${q(t.glyph || '#FFFFFF')}`];
  if (t.line) parts.push('line: true');
  if (t.glyphCycle) parts.push(`glyphCycle: [${t.glyphCycle.map(q).join(', ')}]`);
  if (t.duo) parts.push(`duo: [${t.duo.map(q).join(', ')}]`);
  if (t.frost) parts.push('frost: true');
  if (t.lineCycle) parts.push('lineCycle: true');
  if (t.lettersOnly) parts.push('lettersOnly: true');
  if (typeof t.radius === 'number') parts.push(`radius: ${t.radius}`);
  if (t.emojiTile) parts.push('emojiTile: true');
  if (t.neu) parts.push('neu: true');
  if (t.glyphStyle) parts.push(`glyphStyle: ${q(t.glyphStyle)}`);
  if (t.gradStroke) parts.push(`gradStroke: [${t.gradStroke.map(q).join(', ')}]`);
  if (t.dots) parts.push('dots: true');
  if (t.wordTile) parts.push('wordTile: true');
  if (t.wordColors) parts.push(`wordColors: [${t.wordColors.map(q).join(', ')}]`);
  if (t.wordStyle) parts.push(`wordStyle: ${q(t.wordStyle)}`);
  if (t.glow) parts.push('glow: true');
  if (t.thick) parts.push('thick: true');
  if (t.ring) parts.push('ring: true');
  out += `        ${q(k)}: WKIconTheme(${parts.join(', ')}),\n`;
}
out += '    ]\n';
out += '    static let vglyphs: [String: [WKGlyphStroke]] = [\n';
for (const [k, strokes] of Object.entries(D.VGLYPHS)) {
  const sw = strokes.map(s => { const { pts, tiny } = vglyphPoints(s); return `WKGlyphStroke(points: [${pts.map(p => `[${r4(p[0])}, ${r4(p[1])}]`).join(', ')}], tinyCircle: ${tiny})`; });
  out += `        ${q(k)}: [\n            ${sw.join(',\n            ')}\n        ],\n`;
}
out += '    ]\n';
out += '    static let vglyphFor: [[String]] = [\n' + D.VGLYPH_FOR.map(p => `        [${q(p[0])}, ${q(p[1])}],`).join('\n') + '\n    ]\n';
out += '}\n';
writeFileSync('Shared/WKData.swift', out);
console.log('WKData.swift', out.length, 'chars; themes', Object.keys(D.THEMES).length, 'iconThemes', Object.keys(D.ICON_THEMES).length, 'glyphs', Object.keys(D.VGLYPHS).length);
